### ISSUE TITLE
Apply backpressure per Kafka partition

### ISSUE THREAD

**Issue by atamborrino** [akka/reactive-kafka#110]
Hi,

I open this issue to discuss about a potential improvement.

For now, when we create a consumer, back-pressure is applied *per Kafka topic*. If the processing of a record of partition 1 is slow (via a .mapAsync for instance), this will block consumption for all other partitions. This can be mitigated by having several deployed clients with the same consumer-group, but I think we should allow parallel/independent consumption of partitions inside the same instance of client. 

Consuming the partitions of a Kafka topic in parallel in quite standard in the Kafka world, as message ordering is only guaranteed per-partition. Apache Samza and the recent Kafka Streams lib follows this approach by mapping the consumption parallelism level to the number of Kafka partitions (see http://docs.confluent.io/2.1.0-alpha1/streams/architecture.html#parallelism-model). Hence partition processing are totally independent and a slowly processed partition does not block all the others.

To do the same with reactive-kafka, a first approach could be the following:
```scala
consumerSource
  .groupBy(maxNbPartitions, msg => msg.partition)
  .mapAsync(1)(yourAsyncProcessing)
  .mergeSubStreams
  .to(consumer.offsetSink)
```

However, this approach has the following drawbacks:
* Independent processing between partitions is limited: once an input buffer for a slowly processed partition is full, all the other partitions are blocked.
* Non-optimal efficiency: when the processing for a partition begin to be slow, the Kafka consumer will still get in a round-robin fashion records for all partitions, even if partition 1 processing is already late and its input buffer is already big. It would be more efficient to *propagate* this backpressure information to the Kafka client itself to tell it to stop fetching from partition 1 for now and concentrate throughput on other partitions.

Thus, I think that if we want real independent back-pressure between partition we can write a new consumer, say "fine-grained", that uses Kafka client 0.9 ConsumerRebalanceListener and Consumption Flow Control (using client.pause(partition) and client.resume(partition), see https://kafka.apache.org/090/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html).

I see this consumer being a Source[Source[Record]]. The wrapper source being a source of partition, the wrapped source being a source of records. This makes quite sense from a Kafka client point of view (with auto-assigned partitions, a Kafka client is really a source of partition where each partition is a source of records).

The code could look like this:
```scala
val perPartitionConsumer = kafka.consumePerPartitionWithOffsetSink(...) // whatever naming
val partitionStream = Source.fromPublisher(perPartitionConsumer.publisher)

partitionStream.map { recordStream =>
    recordStream
      .mapAsync(1)(yourAsyncProcessing)
}
.flatMapMerge(maxNbPartitions, identity)
.to(perPartitionConsumer.offsetSink)
```

With this, we have true per-partition async backpressure. This has also the benefits of exposing the assign/unassign of partitions to the lib users if they want to do something upon these events.

Do you think it will be interesting to have such fine-grained consumer in the API? If we agree on it, I'll be happy to code it and do a PR.

**Comment by 13h3r** [comment]
@atamborrino thanks for the idea. Right now we are discussing how new API for reactive-kafka will looks like - akka/akka-meta#14 and akka/akka-meta#13.

In general I like your idea, but first we have to agreed how very basic API will looks like.

Also I worry about how pause/resume is implemented in kafka client. Client prefetches some data and if topic/partition is paused just drop this data which is inefficient. May be this will be fixed in 0.10.

**Comment by atamborrino** [comment]
@13h3r ok thanks for your feedback. Ok we'll wait first for the new basic API. In the meantime I'll dig into Kafka client pause/resume implementation to see if it really fulfil our needs.

**Comment by 13h3r** [comment]
Also you may be interested in my question - https://mail-archives.apache.org/mod_mbox/kafka-users/201602.mbox/%3CCALOoMxw68yUgdrZpPrHT1FJLA+azTbxe=EuDhiYjtHPbrgQd4Q@mail.gmail.com%3E

**Comment by 13h3r** [comment]
I like API which can provide Source[(TopicInfo, Source[Messages])] because it also exposes dynamically assigned partitions in a stream manner.

The problem here is in kafka client which is not thread safe. Partition related sources should coordinates somehow with one materialized kafka client and concurrently call pause/resume.

**Comment by atamborrino** [comment]
Yep me too. But it will be ```Source[(PartitionInfo, Source[Messages])]```, is it not?

Concerning the implementation, when I thought about it with the actor / RS Source implementation, I was thinking of a main ActorPublisher[(PartitionInfo, Source[Messages])] which have the kafka consumer client and create a child actor ActorPublisher[Messages] per partition assigned, dynamically. Child actor can send Ack and/or Nack to propagate per-partition backpressure to their parent actor.

But as far as I understand, we prefer to use the GraphStage API to create a Source right? In that case, I'll have to dig a little bit in the GraphStage API to see how we can implement it.

**Comment by 13h3r** [comment]
> Yep me too. But it will be Source[(PartitionInfo, Source[Messages])], is it not?

yes

AFAIU graph stage API is for complex shapes (like 3 in and 4 out with some complex semantic). Actor based API is another way to implement `Source` and `Sink`. @ktoso, @patriknw please confirm am I right about it or not.

I have another thought about backpressure per partition. Are multiple graphs solve this? If you can backpressure each partition then you should be able to process each partition independent from others. What if you create multiple graphs and each graph assign one partition for itself? Will it solve your case?

**Comment by patriknw** [comment]
yes, we will use GraphStage for the implementation

**Comment by danielwegener** [comment]
I can second this request. Back pressure per partition is important if one wants to `mergeSort` a view of the whole topic. I had this problem roughly a year ago when we needed a deterministic replayable (single) consumer that consumed all partitions in parallel (filtered 99% of the messages away) and then merge-sorted them by event-time and then grouped/aggregated the _realigned_ stream. Since messages are not really always perfectly distributed over all partitions (especially if they are partitioned by a _business_ key), they do not always play back at the same speed. Plus: If one partitions producer dies or becomes slow, all other partitions should be back-pressured and wait for the slow producer to catch up.

 I guess its possible to create this with one dedicated consumer per partition (back then I used the simple consumer api), but an API that creates a source per partition would be really helpful in such cases and emphasizes the _I am still in a partitioned world_-pattern like samza and kafka streams do it.

**Comment by atamborrino** [comment]
> I have another thought about backpressure per partition. Are multiple graphs solve this? If you can backpressure each partition then you should be able to process each partition independently from others. What if you create multiple graphs and each graph assign one partition for itself? Will it solve your case?

When you say "multiple graphs", you mean a graph source with multiple outlets? The problem of this is that the number of outlets is fixed, whereas the assignment / unassignment of Kafka partitions is dynamic. Hence I think a Source of Source models well this behaviour.

**Comment by 13h3r** [comment]
> When you say "multiple graphs", you mean a graph source with multiple outlets? The problem of this is that the number of outlets is fixed, whereas the assignment / unassignment of Kafka partitions is dynamic. Hence I think a Source of Source models well this behaviour.

No, I mean running multiple sources with multiple underlying kafka clients. Multiple kafka clients will be balanced by kafka.

**Comment by atamborrino** [comment]
I don't think this is a good idea because in that case re-balancing between nodes will not be efficient: if we launch X clients on the first node (X = nbPartitions), we have backpressure per partition but I think launching 30 Kafka clients on a single node is an anti-pattern with bad performance.
Even worse, when you add a second nodes, this second nodes will not receive any partition to process as the 30 clients of the first node already have one partition each.

**Comment by 13h3r** [comment]
> Even worse, when you add a second node, this second node will not receive any partition to process as the 30 clients on the first node already have one partition each.

Agreed. Lets reject this idea

**Comment by 13h3r** [comment]
Also, we may be interesting to expose stream per-partition. Partition are used to limit processing scope and it is possible to perform windowed operations on per partition basis. Could we expose `SubFlow` from kafka consumer?

**Comment by atamborrino** [comment]
A ```Subflow``` could do the job instead of a ```Source[Source]```, but in that case the api user can not react to the assignement/unassignement of partitions, can he?

**Comment by 13h3r** [comment]
There is discussion about this in PR - https://github.com/akka/reactive-kafka/pull/139

**Comment by atamborrino** [comment]
Great!

**Comment by 13h3r** [comment]
done
