### ISSUE TITLE
Format[T] instead of Kafka Deserializer, Serializer.

### ISSUE THREAD

**Issue by RayRoestenburg** [akka/reactive-kafka#114]
What do you guys think of having  the serializer and deserializer use type classes?

So basically 
```scala
object ConsumerProvider {
  def apply[K, V](host: String, keyDe: Deserializer[K], valueDe: Deserializer[V]): ConsumerProvider[K, V] = {
```

Becomes something like 
```scala
object ConsumerProvider {
  def apply[K, V](host: String)(implicit keyDe: Deserializer[K], valueDe: Deserializer[V]): ConsumerProvider[K, V] = {
```
I’ve found it unlikely to only use the Deserializer or the Serializer in an app, and it is convenient to define them both in one location, so I think a `Format[T]`is nicer (even for the purpose of testing your ser / deser):

```scala
trait Format[T] {
  def serialize(t: T): Array[Byte]
  def deserialize(bytes: Array[Byte]): Either[Exception, T]
}
```

Also, Kafka’s `Serializer` and `Deserializer` are a bit nutty if you ask me, with `configure` and `close` on it. 
It’s very easy to code a  wrapper around `Format[T]` for a kafka serializer and deserializer.
Something like:

```scala
  class KafkaSerializer[T](format: Format[T]) extends Serializer[T] {
    def configure(configs: java.util.Map[String, _], isKey: Boolean) = {}
    def serialize(topic: String, data: T): Array[Byte] = format.serialize(data)
    def close(): Unit = {}
  }

  class KafkaDeserializer[T](format: Format[T]) extends Deserializer[T] {
    def configure(configs: java.util.Map[String, _], isKey: Boolean) = {}
    def deserialize(topic: String, data: Array[Byte]): T = format.deserialize(data) match {
      case Left(e) => throw e
      case Right(r) ⇒ r
    }
    def close(): Unit = {}
  }
```
Which would be used internally.

And you could provide default formats for String, Array[Byte], etc.

So you get:
```scala
object ConsumerProvider {
  def apply[K, V](host: String)(implicit keyDe: Format[K], valueDe: Format[V]): ConsumerProvider[K, V] = {
```
And the same format is used for producer (omitted here).

I guess it depends how much you feel like 'improving' (if this is an improvement) to the standard Kafka way of doing things.

**Comment by patriknw** [comment]
Thanks for the idea. Serialization is absolutely something I would like to look at. I was also thinking about if it would make sense to have integration with Akka serializers?

**Comment by RayRoestenburg** [comment]
Yes, that could make sense too. The serialization support in Kafka is very minimal. If you could leverage the Akka serializers that would be great, Is the EventAdapters only for persistence BTW? I'm sure users will run into that at some point (several versions of serialized format) There is nothing like that I know of in Kafka.

**Comment by RayRoestenburg** [comment]
I always liked the way unmarshallers etc work in spray, if the stuff is in implicit scope, it just works. Akka serialization also just works if you configure it right, little different maybe, but still. Being able to send a message to kafka and have the lib pick the right serializer by some rules is very nice I think.

**Comment by RayRoestenburg** [comment]
Just noticed kafka-3336 ..

**Comment by patriknw** [comment]
Another thought, perhaps we should not build the serialization on top of kafka-clients interfaces. Instead serialize/deserialize as a `map` stage of the ordinary stream and keep the consumer/producer serializer as the primitive `Array[Byte]` (and `String`, `Integer`) serializer.

Then you can make serializers that are usable in other contexts. Then you can also perform serialization in parallel (pipelined and also with `mapAsync`).

Perhaps that is what you mean, @RayRoestenburg?

**Comment by RayRoestenburg** [comment]
Yes, in general, though I think you found another improvement there I
didn't think of! Sounds good.

**Comment by patriknw** [comment]
Which also means that this is not an issue for this project, but should be included in Akka or another library. We might also need some new serialization abstraction for the new Akka remoting (based on streams). Do you agree? Can we close?

**Comment by RayRoestenburg** [comment]
Yes you can close

**Comment by patriknw** [comment]
thanks
