### ISSUE TITLE
Stream source from example code isn't working for me (0.11.0-SNAPSHOT)

### ISSUE THREAD

**Issue by gzoller** [akka/reactive-kafka#120]
Hello,

Trying to adapt sample code in test but not successful.  I'm using this as a producer:

    val kafka = new ReactiveKafka()
    val producer = ReactiveKafkaProducer[Array[Byte], String](ProducerProperties(
      bootstrapServers = "192.168.99.100:9092",
      topic = "lowercaseStrings",
      valueSerializer = new StringSerializer()
    ))
    producer.producer.send(new ProducerRecord("lowercaseStrings","foo"))
    producer.producer.send(new ProducerRecord("lowercaseStrings","bar"))
    producer.producer.send(new ProducerRecord("lowercaseStrings","blather"))

I can see the offsets in my "lowercaseStrings" topic on my Kafka server are set appropriately to these sent messages, so I'm extending some faith that these published ok.

Now I try to consume with this code lifted from the examples in test:

```
 val provider = ConsumerProvider(
    "192.168.99.100:9092",
    new ByteArrayDeserializer,
    new StringDeserializer
    )
    .setup(TopicSubscription("lowercaseStrings"))
    .groupId("c5")
    .autoCommit(false)
    .prop("auto.offset.reset", "earliest")

  val graph = GraphDSL.create(Consumer[Array[Byte], String](provider)) { implicit b => kafka =>
    import GraphDSL.Implicits._
    type In = ConsumerRecord[Array[Byte], String]
    val dummyProcessor = Flow[In].map{ x => println("Message: "+x); Thread.sleep(1000); x }

    kafka.messages ~> dummyProcessor ~> Consumer.record2commit ~> kafka.commit
    SourceShape(kafka.confirmation)
  }

  val control =
    Source.fromGraph(graph)
      .mapAsync(8)(identity)
      .to(shutdownAsOnComplete)
      .run()

  sys.addShutdownHook {
    control.stop()
    println("Waiting for stop!")
    Await.result(as.whenTerminated, 30.seconds)
    println("AS stopped!")
  }
```

I've added a println to the flow to see my output and changed the topic name but otherwise its the same.

When run, I don't see my topic's stored contents and my Kafka offsets on the server don't change.  I do see these output errors:

```
[default-akka.actor.default-dispatcher-3] INFO org.apache.kafka.clients.consumer.internals.AbstractCoordinator - Marking the coordinator 2147483647 dead.
[default-akka.actor.default-dispatcher-3] INFO org.apache.kafka.clients.consumer.internals.AbstractCoordinator - Marking the coordinator 2147483647 dead.
[default-akka.actor.default-dispatcher-3] INFO org.apache.kafka.clients.consumer.internals.AbstractCoordinator - Marking the coordinator 2147483647 dead.
...streams on indefinitely...

```

What am I missing?

**Comment by gzoller** [comment]
More details:  Running Kafka version 0.8.2.1 and Akka 2.4.2.

**Comment by 13h3r** [comment]
Version 0.11 uses client for kafka 0.9. Could you try it on kafka 0.9.0.1?

**Comment by gzoller** [comment]
Bingo.  That worked cleanly.  Aaaaand.... there was a note to that effect in the readme.  My bad, sorry.
This looks like an exciting project.  Look forward to its ongoing evolution.
