### ISSUE TITLE
Kafka Regex for Whitelist or Blacklist isn't working for 0.9.x 

### ISSUE THREAD

**Issue by dlynam01** [akka/reactive-kafka#140]
I'm attempting to stream from a number of topics using a white list on v0.10.1 . I've configured the ConsumerProperties and have supplied a regex as my topic. The scala doc in the consumerProperties says that it only supports whitelist "This topic is a whitelist only but can change with re-factoring below on the filterSpec" 

This scala doc is incorrect. The subscribe() function that is called  underneath uses an exact list of topics and doesn't use any regex patter.

**Comment by 13h3r** [comment]
Now you can subscribe with pattern
