### ISSUE TITLE
Manual commits are not handled appropriately after a consumer rebalance in 0.8 branch

### ISSUE THREAD

**Issue by evans-ye** [akka/reactive-kafka#141]
Hi all, I've looked into #118 and I'm experiencing the same issue on 0.8.3 as well. I believe the issue hasn't been fixed in 0.8.8 yet. The following is my investigation:

Consider that a consumer originally owns 2 partitions. The partitionOffsetMap and committedMap currently are:
partitionOffsetMap("a.1" -> 5, "a.2" -> 10)
committedOffsetMap("a.1" -> 5, "a.2" -> 10)

When rebalanced, "a.2" has been reassigned to another consumer, while "a.1" is still owned by this consumer. And then, the next scheduled commit operation has been executed with the following context:

partitionOffsetMap("a.1" -> 30, "a.2" -> 10) # "a1" has been updated by this consumer
committedOffsetMap("a.1" -> 5, "a.2" -> 10)
**************************************************
offsetMapToFlush("a.1" -> 30)

After committed, we fetch back the newest committed offsets as a resultOffsetMap, asume it looks like this:
resultOffsetMap("a.1" -> 31, "a.2" -> 41) # "a.2" has been processed by another consumer

Then we update the committedOffsetMap with this code:
committedOffsetMap = OffsetMap(committedOffsetMap.map ++ resultOffsetMap.map.mapValues(_ - 1))

So the new committedOffsetMap is:
committedOffsetMap(a.1 -> 30, a.2 -> 40)

When the next scheduled commit operation has been executed. Now the issue happened here:

partitionOffsetMap("a.1" -> 50, "a.2" -> 10) # "a.2" hasn't being changed
committedOffsetMap("a.1" -> 30, "a.2" -> 40) # "a.2" has been updated to 40 by resultOffsetMap
**************************************************
offsetMapToFlush("a.1" -> 30, , "a.2" -> 10) # "a2" still gets generated!!!!

The issue keep resetting the committed offset to 10, while another consumer keep updating the offset to the newest processed offset. If you got a bad luck, you'll get the old offset when stream restarted, then lots of message will be duplicated.

CMIIW, thanks!

**Comment by julianhowarth** [comment]
We're seeing this issue on the 0.8 branch too

**Comment by kciesielski** [comment]
@evans-ye Thank you very much for this deep analysis. I'm working on this issue now.

**Comment by evans-ye** [comment]
The PR https://github.com/akka/reactive-kafka/pull/144 is the fix in our private branch to unlock our project progress.

**Comment by kciesielski** [comment]
Fixed in #144, released with 0.8.8
