### ISSUE TITLE
Performance issue 

### ISSUE THREAD

**Issue by l15k4** [akka/reactive-kafka#147]
Hey,

I was following the samples in Readme and they work although they are insanely slow, it takes 17 seconds to pipe 100 messages from topic1 to topic2 and 125 seconds with 1000 events 

https://gist.github.com/l15k4/5cdd6be19ec2fcb9a3a32c23f0f6866c

I tried that with `docker run --rm -p 9092:9092 -p 2181:2181 spotify/kafka` instead of the embedded one...

Am I doing something wrong? Or is it a matter of setting kafka differently ?

**Comment by patriknw** [comment]
Thanks for trying that and reporting. Validating performance is indeed something we must do before a final release, see #123

**Comment by l15k4** [comment]
@patriknw  I found that the bottleneck is the consumer : 
https://gist.github.com/l15k4/5cdd6be19ec2fcb9a3a32c23f0f6866c#file-reactivekafkasuite-scala-L54-L58

which is consuming 5 messages per second. The Producer and "pipe" is super-fast and finishes quickly but the Consumer is super slow and even after all messages are emitted it goes 5 messages/sec...

**Comment by patriknw** [comment]
I can understand that offset committing is slow, and that is why batching of commits should be used. It's anyway important that the single commits are decent. 5 messages per second is not decent. 125 is also really bad.

**Comment by kciesielski** [comment]
Just for the record: I modified the gist a bit in order to make sure we're only measuring the final consumer: https://gist.github.com/kciesielski/8a07f1562d25e497bdb5b22d1c71b55c
Running on my local machine gave following results:
With embedded Kafka:
plainSource 100m/2s, 1000m/2s
atMostOnceSource 100m/5.5s, 1000m/13s

With local Kafka:
plainSource 100m/0.4s, 1000m/0.4s
atMostOnceSource 100m/2s, 1000m/12-13s

Note that this includes time needed to connect.

**Comment by avakhrenev** [comment]
Note that you can't fetch more than `max.partition.fetch.bytes` * `partitionCount` / `pollInterval` bytes per unit of time. I would suggest to set `pollInterval` to zero and try again.

**Comment by l15k4** [comment]
Ok, I changed to `flozano/kafka:0.9.0.0` and `IN -> topic1 -> topic2 -> OUT` now performs 25 000 m/s with plainSources ... sorted out, thank you !

**Comment by kciesielski** [comment]
@l15k4 Is `flozano/kafka:0.9.0.0` some custom docker image? By the way, the newest version of Kafka is 0.9.0.1, it may contain some performance fixes.

**Comment by l15k4** [comment]
@kciesielski yeah https://github.com/flozano/docker-kafka ... They have a bug in the `latest`/`0.9.0.1` build. I'm building my own image as there is no image out there that would bundle ZK and one could easily change server.properties, which is implemented here https://github.com/wurstmeister/kafka-docker/blob/master/start-kafka.sh#L29-L40

**Comment by kciesielski** [comment]
@l15k4 Interesting, is that a bug in Kafka itself or just a bug in docker image?

**Comment by l15k4** [comment]
@kciesielski In the image https://github.com/spotify/docker-kafka/pull/34#issuecomment-220063939

**Comment by kciesielski** [comment]
I see, thanks :)
