### ISSUE TITLE
Way to create reusable producers

### ISSUE THREAD

**Issue by rgarciate** [akka/reactive-kafka#154]
I've going over the reactive-kafka code and I have seen that a KafkaProducer is created everytime in flow method (akka.kafka.scaladsl.Producer, line 54 [https://github.com/akka/reactive-kafka/blob/ff5cf9d84904a0ecbb5246c9bce4784593bc9ffd/core/src/main/scala/akka/kafka/scaladsl/Producer.scala#L54 ]).
Creating one Producer everytime that a Flow is created has hard impact on performance.
Maybe there should be a way to create the KafkaProducer once and reuse it.

Issue opened as @13h3r 's suggestion: https://gitter.im/akka/reactive-kafka?at=574baad5a78d5a256e3900aa

**Comment by 13h3r** [comment]
I will implement this after #139 in the same manner

**Comment by patriknw** [comment]
@13h3r What is the status here?

**Comment by 13h3r** [comment]
@patriknw not even started yet :(

**Comment by patriknw** [comment]
Thanks for the update. Do you think this will influence the API or can it be added afterwards with current API? I'm thinking if it has to be done before releasing 0.11 or can be added afterwards without breaking the API.

**Comment by 13h3r** [comment]
I think we can add it afterwards without breaking backward compatibility
