### ISSUE TITLE
Not specifying group.id causes error

### ISSUE THREAD

**Issue by l15k4** [akka/reactive-kafka#155]
Hey,

why is specifying consumer `group.id` mandatory in reactive-kafka? Not doing so leads to : 
```
21:48:20.000 ERROR o.a.k.c.c.i.AbstractCoordinator - Attempt to join group  failed due to: The configured groupId is invalid
21:48:20.006 ERROR a.k.i.PlainConsumerStage$$anon$2 - Error in poll
org.apache.kafka.common.errors.ApiException: The configured groupId is invalid
[ERROR] [06/05/2016 21:48:20.008] [AkkaSuiteSystem-akka.kafka.default-dispatcher-6] [akka://AkkaSuiteSystem/user/StreamSupervisor-0/flow-0-2-unknown-operation] Error in stage [akka.kafka.internal.PlainConsumerStage@16336a62]: The configured groupId is invalid
org.apache.kafka.common.errors.ApiException: The configured groupId is invalid
21:48:21.035 ERROR o.a.k.c.c.i.AbstractCoordinator - Attempt to join group  failed due to: The configured groupId is invalid
21:48:21.037 ERROR a.k.i.PlainConsumerStage$$anon$2 - Error in poll
org.apache.kafka.common.errors.ApiException: The configured groupId is invalid
```
It can be reproduces even on the README examples if you remove `group.id` ...

I don't use any offset management

**Comment by 13h3r** [comment]
Could you please post full example?

**Comment by l15k4** [comment]
@13h3r   https://gist.github.com/l15k4/8f09b62f41eef019d07051798c495064

It only works if you add `.withGroupId("group1")` to consumer settings.

**Comment by l15k4** [comment]
Guys any update on this? Am I doing something wrong?

**Comment by kciesielski** [comment]
@l15k4 groupId seems to be mandatory for Kafka 0.9.0.x consumers https://issues.apache.org/jira/browse/KAFKA-2648 so you have to set it with Reactive Kafka too.

**Comment by l15k4** [comment]
@kciesielski Thanks!

**Comment by l15k4** [comment]
@kciesielski What I still don't understand about making groups mandatory is that if you don't need groups then you don't need kafka to commit offset at all... Because committing consumer offset is needed  due to consumer groups... Otherwise single consumer is memoizing its offset itself.

So enforcing presence of consumer groups is enforcing consumer offset persistence on Kafka server...

My colleague is using Python client and there if you don't specify group.id then offset is not committed at all on kafka server...

**Comment by kciesielski** [comment]
@l15k4 Setting group.id is a separate thing that setting whether you want to commit automatically or manually. I don't know why on python `group.id` is not mandatory while the Java client requires it. Maybe you can ask on Kafka Users mailing list (http://kafka.apache.org/contact.html)?
