### ISSUE TITLE
Consumer is not able to receive messages from Kafka produced with reactive Kafka Producer 

### ISSUE THREAD

**Issue by seanyinx** [akka/reactive-kafka#156]
Without restarting embedded Kafka in each case of unit testing, reactive Kafka consumer is only able to receive message produced by reactive Kafka producer in the first case but not the rest and those messages produced can all be seen in Kafka log.

However, if embedded Kafka is restarted in each case, this issue disappears. If a Kafka producer created from ProducerSettings is used to send messages, this issue also disappears.

I made three tests to show this issue in [reactive-kafka-unit](https://github.com/seanyinx/reactive-kafka-unit)
**KafkaNoProducerNoRestartTest.scala** not using reactive Kafka producer and not restarting Kafka before each test case

**KafkaReactiveNoRestartTest.scala** using reactive Kafka producer but not restarting Kafka before each test case (**FAIL**)

**KafkaRestartForEachTest.scala** using reactive Kafka producer and restarting Kafka before each test case

**Comment by kciesielski** [comment]
Thanks for reporting this. As a workaround, can you consider switching from `"com.github.charithe" % "kafka-junit" % "2.1" % "test"` to https://github.com/manub/scalatest-embedded-kafka? This is the library we use in our tests, it has a very similar API.

**Comment by seanyinx** [comment]
thank you for providing the kafka unit testing library.

i updated my project with the library you provided above, but the tests seem to have the same issue running with this library too. 

you may see the changes here: [reactive-kafka-unit](https://github.com/seanyinx/reactive-kafka-unit)

**Comment by glacier3** [comment]
Hi @kciesielski 

Thanks for your hard work on this great project. 

I'm also encountering the same issue as @seanyinx ,  here is my code,
` final ActorSystem system = ActorSystem.create("searchIndexAkkaSystem");
        final LoggingAdapter logger = system.log();
        final ConsumerSettings consumerSettings = ConsumerSettings.create(system, new StringDeserializer(), new StringDeserializer(),
                ConsumerSettings.asSet(envTopics.toArray(new String[0])))
                .withBootstrapServers("<remoteIP>:9092")
                .withGroupId("group2")
                .withProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
        final ActorMaterializer materializer = ActorMaterializerImpl.create(system.systemImpl());

        Consumer.committableSource(consumerSettings.withClientId("fulltext_search_consumer")).runForeach(
                new Procedure<ConsumerMessage.CommittableMessage>() {
                    @Override
                    public void apply(ConsumerMessage.CommittableMessage msg) throws Exception {
`

The consumer is listening on a remote kafka server, and the consumer can only receive one message from kafka. 

The wired thing is that if I change .withGroupId("group2") to .withGroupId("group1"), it works very OK again. Could you please tell me if I can only use 'group1' as the group id?

**Comment by glacier3** [comment]
I have written a ruby testing code with gem https://github.com/zendesk/ruby-kafka

it works without any issue, here is the code:

```
kafka = Kafka.new(seed_brokers: ["remote ip:9092"])

consumer = kafka.consumer(group_id: "group2", offset_commit_interval: 5, offset_commit_threshold: 100)

consumer.subscribe("development-model-events")
  .subscribe("qa-model-events")
  .subscribe("production-model-events")

consumer.each_message do |message|
  puts message.topic, message.partition
  puts message.offset, message.key, message.value
end
```

**Comment by kciesielski** [comment]
@seanyinx When you start your producer stream with `.run()`, you immediately initialize a consumer stream. The consumer connects first before the producer creates the topic and this causes your problem. 
See my PR https://github.com/seanyinx/reactive-kafka-unit/pull/1 with tweaks. Feel free to reopen this issue if such problems keep appearing after adhering to fixes recommended in the PR.

**Comment by seanyinx** [comment]
thank you very much, it worked!
