### ISSUE TITLE
Consumer won't read any message with auto.offset.reset=latest

### ISSUE THREAD

**Issue by l15k4** [akka/reactive-kafka#158]
Hey,

I would expect the consumer to read 10 messages. But instead it doesn't read any message and it waits. I'm using freshly started kafka 0.9.0.1 container.

https://gist.github.com/l15k4/29c816f3a773c38dc8d594457de8fa26

Basically this behavior prevents people from using auto.offset.reset=latest entirely.

**Comment by kciesielski** [comment]
In the gist you start producer and consumer stream at the same time. It is possible that your consumer connects after the stream gets populated by producer. What happens if you add a sleep before `val sf`?

**Comment by l15k4** [comment]
Hey @kciesielski,

I tried to put `Thread.sleep(1000)` in between P & C, but it is the same outcome...

**Comment by kciesielski** [comment]
Sorry, I meant:
1) put consumer stream initialization first
2) add sleep
3) start producer stream

**Comment by l15k4** [comment]
That works, but then it would be hard to implement a consumer consuming topic with existing messages and leverage `auto.offset.reset=latest` ... One would need to start it with `auto.offset.reset=earliest` initially and then in case of restart/failure it would need to be started with `latest` ... Or what am I missing here ?

**Comment by kciesielski** [comment]
`auto.offset.reset` is used if you connect to a topic when your consumer group hasn't committed any messages yet. If you use `auto.offset.reset=latest` and connect to a topic with existing messages, you will not consume these messages, only new messages that will appear after you connect. Then, if you need to reconnect, you will start from last committed position.

**Comment by l15k4** [comment]
Ah, forgive my kafka newbiness, thank you !

P.S. I'd test this stuff with the java client before reporting but it is such a lowlevel API ... Next time I will !

**Comment by l15k4** [comment]
@kciesielski Hey, since we opened this context ... Can I ask you how would you implement this relevant use case? 

Having `Publisher` and N `Subscribers`, publisher cannot start publishing to a topic until it knows that all subscribers started consuming that topic ... What is the best way for it to get that information? ( without leveraging Zookeeper for instance) Does Kafka provide means to do that ?

This happens before relationship makes it kinda hard ...

**Comment by kciesielski** [comment]
@l15k4 This doesn't look like a use case for Kafka. PM me on Gitter and we'll talk about it. https://gitter.im/

**Comment by l15k4** [comment]
Anyway, I started using `latest` because `earliest` most probably doesn't work in `reactive-kafka` as it should. If you look at this code : 
https://gist.github.com/l15k4/442a7f6a493a828b528d838d5fb28c64#file-reactivekafkasuite-scala-L54-L63

Then the second start of the same client should imho start from offset `6` but it starts from `0`

**Comment by l15k4** [comment]
My bad, I didn't call `msg.committableOffset.commitScaladsl()`
