### ISSUE TITLE
Error handling with new API

### ISSUE THREAD

**Issue by aselamal** [akka/reactive-kafka#161]
Issue #41 described some examples of how to do error handling but Its unclear to me how to do this with the new API. One of the things I'm not sure on is how to get an actor reference out of the new API so I can make a supervisor actor.

So basically How to adapt the previous examples of error handling to the new API, or even another way of doing the error handling.

Here is how I'm creating my producer:
```scala
 val topic = "myTopic"
    implicit val actorSystem = ActorSystem("ReactiveKafka")
    implicit val materializer = ActorMaterializer()

    import akka.kafka._
    import akka.kafka.scaladsl._
    import org.apache.kafka.common.serialization.{ByteArraySerializer, StringSerializer}

    val producerSettings = ProducerSettings(actorSystem, new ByteArraySerializer, new StringSerializer)
            .withBootstrapServers("localhost:9092")
    val bufferSize: Int = 1000
    val messageQueue = Source.queue[Message](bufferSize, OverflowStrategy.backpressure).map(msg =>
        new ProducerRecord[Array[Byte], String](topic, Json.toJson(msg).toString()))
            .to(Producer.plainSink(producerSettings)).run()

```

**Comment by salex89** [comment]
I want to contribute with the same question, only regarding the consumer. In a simple stream where a consumer takes a message and it is stored into a database or sent to API, if the database or API fails, I found no way to reconsume the message automatically. When the stream is restarted (manually, the whole app), the uncommited messages are consumed again. I would like to program this behavior. The current decider implementation for the streams only restarts the current stage, as far as I see it.

**Comment by 13h3r** [comment]
@aselamal could you specify what behavior you want to achieve?
@salex89 to reconsume the message you have to commit offset after your api calls. To achieve exactly one guarantee you need to update offsets together with your data in transaction manner

**Comment by aselamal** [comment]
Hello @13h3r ,

I guess essentially what i'm trying to achieve is what to do if the initially configured kafka brokers go down. I want to be able to handle this by having a chance to look to see if any new brokers are available (checking with service discovery client) and then restart the producer sink with this configuration, also ideally if possible not losing any messages as they can buffer to a configured size and hopefully the producer can recover in time before the buffer fills up.

**Comment by 13h3r** [comment]
The idea of reactive kafka is to use akka-stream's error propagation mechanic. In akka-streams you should use sink and check for abnormal stream completion. In your example you should use `toMat(Producer.plainSink(...))(Keep.both)` to have a `Future` that represents stream completion. 

Feel free to reopen if you still have questions.
