### ISSUE TITLE
Add the ability to pause a consumer if the internal buffer is above a threshold

### ISSUE THREAD

**Issue by jpeel** [akka/reactive-kafka#167]
It would be really nice to set a threshold for the internal buffer size of consumers. With PR #139 merged in, the consumer is polled periodically and any new data is added to the existing internal buffer to be sent downstream upon request which is a great improvement upon how it previously worked where the consumer would only be polled if a pull was received from downstream. However, if data gets backed up downstream for a time, it would be nice if the consumer would be paused when the buffer is above a configurable threshold and is resumed when the buffer falls back below the threshold. The poll needs to still continue to be done while the consumer is paused so that the heartbeat is sent to the brokers, but no data will be returned.

**Comment by 13h3r** [comment]
@jpeel current implementation fetch data only for sources that has demand. If you do not have any demand no messages will be fetched during poll. Could you provide an example of continuously fetching?

**Comment by jpeel** [comment]
The current implementation (as of commit d3d50d1db105231d142d77eb0cfd85c36a96257b) polls after the first pull on the source and continues to poll every polling interval (config setting) unless there is a pull that initiates a poll before the timer has fired. I actually think that this is the correct way for it to run because the heartbeat is tied to the poll. Otherwise, there can be situations where the kafka consumer is starved due to the stream taking too long to process the current batch of messages polled from the consumer and this results in the heartbeat being sent after longer than the session timeout which means that the brokers will have deemed the consumer as down. I have seen this with a project I work on when using the old version of the reactive-kafka consumer where there were times when we wanted to intentionally slow the flow but would be able to catch up with the flow of messages after the temporary slow down.

It is better to pause the consumer when either the buffer is beyond a certain number of events or when it is not empty. Maybe there is a better metric to know when the consumer should be paused.

**Comment by 13h3r** [comment]
@jpeel pay attention that during every poll we pause partitions that does not demand new messages.

**Comment by 13h3r** [comment]
https://github.com/akka/reactive-kafka/blob/master/core/src/main/scala/akka/kafka/KafkaConsumerActor.scala#L156

**Comment by jpeel** [comment]
Yes, I see now. I saw that line before, but missed the line where the topic partitions are removed from the partitions to fetch after a poll. Thank you for your replies and great work on this project. I'll close this issue.
