### ISSUE TITLE
automatic partition assignment not so automatic

### ISSUE THREAD

**Issue by patriknw** [akka/reactive-kafka#171]
I tried the the automatic partiton assignment for a `committableSource`. Two partitions, one topic. Two consumers (different clientId and same groupId).

When I start both clients at the same time the two partitions are balanced as expected between the two clients. Then shutting down one of them, the rebalance doesn't work automatically, the remaining client continues to receive the original partition only. 

Log message:

    "Attempt to heart beat failed since the group is rebalancing, try to re-join group"

I think there is similar problem when adding more consumers.

For reference: http://stackoverflow.com/questions/27181693/how-does-consumer-rebalancing-work-in-kafka

**Comment by 13h3r** [comment]
@patriknw could you share code snippet? Did you shutdown correctly? How long did you wait for rebalance?

**Comment by patriknw** [comment]
I don't shutdown, I `ctrl-c` and expect that to work. I did some more testing now and it seems to solve itself after a while, I was not patient enough. Thanks for listening :)
