### ISSUE TITLE
allow manual commit with plainPartitionedSource

### ISSUE THREAD

**Issue by mazorigal** [akka/reactive-kafka#181]
Hi,

it would be nice to be able use manual commit to external storage using kafka rebalancing functionality.

based on the Exactly-once Kafka Dynamic Consumer via Subscribe (One and Only One Message Delivery) example:
https://dzone.com/articles/kafka-clients-at-most-once-at-least-once-exactly-o

also as described here:
http://kafka.apache.org/0100/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#rebalancecallback

Thanks,

**Comment by 13h3r** [comment]
The problem here is absence of API to set offset after partition is assigned. All other cases may be handled with partitionedSources

**Comment by 2m** [comment]
Closing this ticket due to inactivity. Please re-open this ticket with more information if you still find the original issue relevant.
