### ISSUE TITLE
Closing over mutable actor state

### ISSUE THREAD

**Issue by johanandren** [akka/reactive-kafka#195]
And mutating it (ouch):
https://github.com/akka/reactive-kafka/blob/master/core/src/main/scala/akka/kafka/KafkaConsumerActor.scala#L98

**Comment by 13h3r** [comment]
This is fine, because callback's called in the same thread as poll called.

**Comment by ktoso** [comment]
How come? https://kafka.apache.org/090/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#commitAsync(org.apache.kafka.clients.consumer.OffsetCommitCallback)
I don't see why this would be the case.

**Comment by johanandren** [comment]
Even if it is executed in the same threadpool, it still isn't safe because the threadpool will contain multiple threads, no?

**Comment by kciesielski** [comment]
I saw that too and discussed with @13h3r. This may seem unsafe but it isn't
because callbacks are called in the same thread. Maybe it could be pointed
out in a comment to clarify.

**Comment by ktoso** [comment]
Same as the *calling* thread? this would make it not async though. 
Where is this configured?

**Comment by 13h3r** [comment]
Yes, the callback will be executed in the thread which called `poll`. This fact is not mention directly in documentation, but it is how kafka client designed.

**Comment by johanandren** [comment]
Uff. So if I understand it correctly, the callback is executed on the thread that later calls `consumer.poll()` and since that always is the actor itself in the actor `poll()` method it is safe?

**Comment by johanandren** [comment]
Darn, didn't see that comment before I wrote mine. Anyways, I'll PR with a comment that clarifies.
