### ISSUE TITLE
Death of Kafka coordinator is not propagated to the stream's termination watch

### ISSUE THREAD

**Issue by slavaschmidt** [akka/reactive-kafka#200]
I'm not sure if it's related to the #150

For following consumer utilising at-most-once semantics:
``` scala
  lazy val source = Consumer.committableSource(settings, topics)
    .mapAsyncUnordered(kafkaParallelism) { msg =>
      val _ = msg.committableOffset.commitScaladsl()
      Future.successful(msg)
    }
```
i'm registering a termination watch like this:
`flow.watchTermination()(onStreamTermination).runWith(source, sink)`

Now, if I shut down Kafka during the long-running test, I can see it is properly detected by observing following in logs:
`INFO  o.a.k.c.c.i.AbstractCoordinator - Marking the coordinator localhost:9092 (id: 2147483647 rack: null) dead for group archiver`

But the termination watch never get's called! 

I'd expect that death of the source is propagated to the stream. If it is wrong expectation, what is a correct way of handling this situation?

**Comment by 13h3r** [comment]
try this:

```scala
  lazy val source = Consumer.committableSource(settings, topics)
    .mapAsyncUnordered(kafkaParallelism) { msg =>
      msg.committableOffset.commitScaladsl().map(_ => msg)
    }
```

**Comment by slavaschmidt** [comment]
thanks, it worked! may I dare to ask for an explanation?

**Comment by 13h3r** [comment]
You just misunderstood how `Future`s works.

`mapAsync` will propagate error if `Future` returned by lambda fail. This may fail:

```scala
val _ = msg.committableOffset.commitScaladsl()
```

You should not drop this `Future` as you did, but should transform as I suggested.

**Comment by slavaschmidt** [comment]
thank you very much!
