### ISSUE TITLE
restart of KafkaConsumerActor not handled

### ISSUE THREAD

**Issue by patriknw** [akka/reactive-kafka#202]
Outstanding requests from `SingleSourceLogic` will never be replied to if the actor is restarted.

Perhaps an simple solution is to send something to them from `postStop` (also invoked by default for restarts), such as an empty `Messages` reply.

**Comment by drewhk** [comment]
> Perhaps an simple solution is to send something to them from postStop (also invoked by default for restarts), such as an empty Messages reply.

This is racy, as there might be registrations in-flight we have not seen yet when postStop is called. I think the usual pattern should be used here (bit simplified, won't compile):

```scala
val subscriptions = new AtomicReference(Nil)

// In consumer stage
def register() = {
  val state = subscriptions.get match {
    case Closed => completeStage()
    case registrations =>
      // cas loop add to registration list
     actor ! PendingWakeups
  }
}
```

In the actor on PendingWakeups one must getAndSet(Nil) to empty the list safely. In postStop() a getAndSet(Completed).foreach(_.close()) will ensure that there are no dangling sources.

This is similar to ActorPublisher, and also the BroadcastHub.

**Comment by patriknw** [comment]
but such in-flight registrations (requests for messages) will be received and handled by the new incarnation of the restarted actor

**Comment by drewhk** [comment]
ah, you are talking about restart, sorry. But then there might be an issue with the completion, we need to check.

**Comment by patriknw** [comment]
I think that is fine, there is watch both ways
