### ISSUE TITLE
failed: IntegrationSpec

### ISSUE THREAD

**Issue by patriknw** [akka/reactive-kafka#203]
The IntegrationSpec is still flaky when running on Travis

```
[info] IntegrationSpec:
[info] Reactive kafka streams
[info] - must produce to plainSink and consume from plainSource
[info] - must resume consumer from committed offset *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsg while waiting for OnNext(36)
```

**Comment by nafshartous** [comment]
@patriknw This may be the same issue that forced me to ignore the batching test #223.  We need some way to have visibility with messages in Kafka running on Travis.

**Comment by patriknw** [comment]
ok, feel free to create a PR with more logging enabled

**Comment by nafshartous** [comment]
After my open PR https://github.com/akka/reactive-kafka/pull/223 is closed I'll create a new dummy PR to use for debugging the Travis-specific build failures.  If someone knows of a better way to debug Travis please let me know.

**Comment by patriknw** [comment]
yes, feel free to continue debugging. Pushing new commits to a PR branch will trigger new Travis build.

**Comment by nafshartous** [comment]
This issue can be closed as the `ignore` has been removed to activate the test.
