### ISSUE TITLE
Wrong validation at ProducerSettings apply method

### ISSUE THREAD

**Issue by glammers1** [akka/reactive-kafka#211]
Version: 0.11-RC1

[Actual] (https://github.com/akka/reactive-kafka/blob/master/core/src/main/scala/akka/kafka/ProducerSettings.scala#L69)

```scala
require(
      keySerializer.isDefined || properties.contains(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG),
      "Value serializer should be defined or declared in configuration"
    )
```

Expected

```scala
require(
      valueSerializer.isDefined || properties.contains(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG),
      "Value serializer should be defined or declared in configuration"
    )
```

`valueSerializer.isDefined` instead of `keySerializer.isDefined`

[ConsumerSettings is ok](https://github.com/akka/reactive-kafka/blob/master/core/src/main/scala/akka/kafka/ConsumerSettings.scala#L125)

**Comment by kciesielski** [comment]
Thanks for reporting!

**Comment by glammers1** [comment]
Could I create PR?

**Comment by kciesielski** [comment]
Of course, you are welcome :) Can you add a test?

**Comment by glammers1** [comment]
Perfect!

**Comment by glammers1** [comment]
I've been trying to reproduce the bug in a test before change the code expecting the wrong behavior but it is not possible because the bug is related with the case in which we pass serializers as parameters (not args config) but one of them are None, however the apply methods with the Option signature for the Serializers are private so we can't call the methods outside the companion object with None values.

However, we can reproduce the error using the `create` method marked as `Java API` in its Scaladoc. This method also calls `apply` at the end but there is a different between this call and the others:

* Using create

```scala
def create[K, V](
    config: Config,
    keySerializer: Serializer[K],
    valueSerializer: Serializer[V]
  ): ProducerSettings[K, V] =
    apply(config, Option(keySerializer), Option(valueSerializer))
```

* Using apply

```scala
def apply[K, V](
    config: Config,
    keySerializer: Serializer[K],
    valueSerializer: Serializer[V]
  ): ProducerSettings[K, V] = {
    apply(config, Some(keySerializer), Some(valueSerializer))
  }
```

Note how `create` calls `apply` using `Option` instead of `Some`, that detail let me to test the bug passing a `null` value as serializer but I think that is not the correct way to test it. I don't know why exists that differences in the calls to apply.

Using `apply` developers couldn't reproduce the bug.

What do you think?

**Comment by patriknw** [comment]
ok, I guess you know that `Option(null) => None` while `Some(null) => Some(null)`

Perhaps the intention was that some Java users are used to passing `null` and we handle that as `None`.

I see two alternatives (and it should be implemented the same for both `apply` and `create`).

1) we allow `null`, e.g. when you want to set the `valueSerializer` but not the `keySerializer`, i.e. use `Option` (how common is this?)
2) we change the api to only have `apply` with `Option` parameters and `create` with `Optional` parameters

I think I vote for 2

**Comment by glammers1** [comment]
Me too, vote for 2.

**Comment by 13h3r** [comment]
+1 for 2

**Comment by kciesielski** [comment]
+1 for 2

**Comment by glammers1** [comment]
I suppose that `create` with Java `Optional` must call `apply` with Scala `Option`. I'm wondering what is the best way to do that because Scala does not support Java 8 until Scala 2.12 and neither `JavaConversions` nor `JavaConverters` supports `Optional` at the time. 

Any ideas?

**Comment by patriknw** [comment]
Converter exists in https://github.com/scala/scala-java8-compat and we already use that library
