### ISSUE TITLE
ProducerSettings should validate key serializer

### ISSUE THREAD

**Issue by dotta** [akka/reactive-kafka#212]
Creating a `ProducerSettings` with a `null` key serializer should fail early with an exception, as any attempt of consuming messages with the created `ProducerSettings` will not work.

Here is a self-contained example that can be used to reproduce the problem.

```
object Test {

  import akka.kafka.scaladsl.Producer
  import akka.actor.ActorSystem
  import akka.kafka.ProducerSettings
  import akka.stream.ActorMaterializer
  import akka.stream.ActorMaterializerSettings
  import akka.stream.scaladsl.Source
  import akka.stream.scaladsl.Flow
  import org.apache.kafka.common.serialization.ByteArraySerializer
  import org.apache.kafka.common.serialization.StringSerializer
  import org.apache.kafka.clients.producer.ProducerRecord

  implicit val system = ActorSystem("ReactiveKafka")
  implicit val materializer = ActorMaterializer(ActorMaterializerSettings(system))

  val producerSettings: ProducerSettings[Null, String] = ProducerSettings(system, null, new StringSerializer)
    .withBootstrapServers("localhost:9092")

  val flow = Flow.fromFunction { (message: Int) =>
    new ProducerRecord[Null, String]("topic-foo", message.toString)
  }
                          
  Source.single(1)
    .via(flow)
    .runWith(Producer.plainSink(producerSettings))

}
```

The stream materialization will result in an exception: `org.apache.kafka.common.config.ConfigException: Missing required configuration "key.serializer" which has no default value.`

The above snippet assumes a Kafka broker is running on localhost:9092.

**Comment by patriknw** [comment]
Thanks for reporting, @dotta 
I think this is a duplicate, or at least very related to https://github.com/akka/reactive-kafka/issues/212

@glammers1 Please take a look at this one also and make sure the PR covers it.

**Comment by dotta** [comment]
@patriknw I think you meant #211. Indeed, it is very similar, but #211 seems to be about the value serializer validation, while the problem I had was with the key serializer. But I suppose it's easy to fix the two tickets together.

**Comment by patriknw** [comment]
yes, copy pasta

**Comment by glammers1** [comment]
Yes, the option 2 in #211 

> we change the api to only have apply with Option parameters and create with Optional parameters

should resolve both issues.

btw, `ConsumerSettings` should be updated in the same manner.
