### ISSUE TITLE
Akka streams graph not working

### ISSUE THREAD

**Issue by robertomoreno** [akka/reactive-kafka#218]
I'm trying to build a graph wich makes a mapAsync from a kafka message, it may throw a ParseException. If so, I want to retry 3 times. In order to achive this I'm using Merge and Partition for a cycling graph. [See this example](https://github.com/robertomoreno/dummy-monitoring-process/blob/master/src/main/scala-2.11/dummy/monitoring_process/service/Boot.scala)

It works well if just flows from Source(List) but not with a Kafka Source.

**Comment by 2m** [comment]
Closing this ticket due to inactivity. Please re-open this ticket with more information if you still find the original issue relevant.
