### ISSUE TITLE
it's blocking

### ISSUE THREAD

**Issue by patriknw** [akka/reactive-kafka#219]
We must re-introduce the dedicated dispatcher because both `send` and `poll` methods are blocking if the broker is not available. `send` returns after timeout (default 60 seconds). `poll` doesn't return at all (at least I had not the patente to wait).

I tried with `sample.scaladsl.AtLeastOnceExample` and `sample.scaladsl.PlainSinkExample` + some printlns in the stages.

The producer dispatcher was removed in https://github.com/akka/reactive-kafka/pull/206

**Comment by drewhk** [comment]
The dispatcher should be on the actor on the consumer side though, but yeah, it looks like the Producer stage must have a dedicated one, too. Sigh, these APIs...

**Comment by drewhk** [comment]
Given that there is already blocking, I still wonder if a spinning-blocking thread approach might be better then...

**Comment by kciesielski** [comment]
@patriknw there's a consumer setting `connections.max.idle.ms` with default value of `540000`  which is 9 minutes. Maybe with lower value the consumer will drop with a timeout exception?

**Comment by patriknw** [comment]
ok, good to know, yeah I didn't wait 9 minutes

**Comment by drewhk** [comment]
Actually we discovered that poll() was blocking (on a NIO selector), but I was under the impression that it is capped by the remaining time from the poll timeout. weeeird.

**Comment by patriknw** [comment]
It is capped to the poll timeout under normal circumstances, but when it can't connect to the broker it is blocking longer. Yeah, weird api.

**Comment by 13h3r** [comment]
@patriknw even more, if you lost connection from consumer to broker during metadata request you will wait infinitely. Also we may have check `wakeup` method which aborts current blocking operation.
