### ISSUE TITLE
KafkaConsumerActor checkOverlappingRequests comparing fromStage to requests map value, not the ActorRef key

### ISSUE THREAD

**Issue by kyal** [akka/reactive-kafka#234]
https://github.com/akka/reactive-kafka/blob/master/core/src/main/scala/akka/kafka/KafkaConsumerActor.scala#L142

This comparison will never succeed due to what I believe is a typo and it should be (ref != fromStage && ...) instead.
As such checkOverlappingRequests would never respond to the requesting actor with an empty set of messages and remove the request. No idea if this behavior is acceptable or not but no reason to perform the check if it can never succeed.

**Comment by kciesielski** [comment]
Thanks for reporting @kyal, this indeed looks like a bug.
