### ISSUE TITLE
Allow setting log levels for consumer and producer

### ISSUE THREAD

**Issue by ChetanBhasin** [akka/reactive-kafka#242]
The default log level is DEBUG, which produces a lot of information that may not be required in all scenarios.
We should probably have a way of defining log level for consumer and producer.

**Comment by kciesielski** [comment]
@ChetanBhasin You can configure your own logging levels. The project doesn't override the defaults, see general docs on how to configure logging for Akka http://doc.akka.io/docs/akka/current/java/logging.html

**Comment by ChetanBhasin** [comment]
@kciesielski Ah, I'm sorry, I should have noticed. Thanks for pointing out.

**Comment by patriknw** [comment]
and if you use a slf4j logging backend you can add logging filters in that config to filter out specific logging
