### ISSUE TITLE
Document error handling requirements

### ISSUE THREAD

**Issue by timcharper** [akka/reactive-kafka#248]
What happens when a consumer / publisher loses connection to a broker? Does the stream need to be restarted? Some notes about the error handling strategies would be helpful so users can plan appropriately.

**Comment by patriknw** [comment]
That should be clarified. Short story is that if it can't reconnect the stream will be failed and you have to restart it, i.e. you have to plan for stream failure.

**Comment by jonathanvm13** [comment]
Hi @patriknw  what is the  way to plan for stream failure ? Using a supervisionStrategy ? Thanks

**Comment by kciesielski** [comment]
@jonathanvm13 @timcharper when a stream fails, you can react accordingly by catching a failing materialized future:
```scala
val done: Future[Done] =
      Consumer.committableSource()
      .runWith(sink)

done.onFailure {
  case NonFatal(e) => restartStream()
}
```

**Comment by patriknw** [comment]
Right, almost all sinks return a materialized value Future or similar for this purpose. Otherwise `watchTermination` can be added.

**Comment by vaaction** [comment]
I think it is right place to write my issue. 
Our protocol requires a response with cpecial code and state if kafka is not available, but I cannot recover state. I can only get exception using the recover function and NotUsed using ....viaMat(Producer.flow(producerSettings))(Keep.both).mapMaterializedValue().
Only addition and complicated stage can help here.
Is there any another easier way?

**Comment by ennru** [comment]
The documentation describes how to use RestartSource and the tests show that the Kafka client code reconnects successfully.
