### ISSUE TITLE
Document Sharing KafkaProducer

### ISSUE THREAD

**Issue by glammers1** [akka/reactive-kafka#249]
After this PR #240, docs could be updated with code examples (there is a TODO).

http://doc.akka.io/docs/akka-stream-kafka/current/producer.html#sharing-kafkaproducer

@iravid ?

**Comment by jacobtardieu** [comment]
I'll be happy to do it!

**Comment by jacobtardieu** [comment]
I think we can close this one too, the doc has been merged!
