### ISSUE TITLE
Use Akka's provided StageLogging

### ISSUE THREAD

**Issue by ktoso** [akka/reactive-kafka#251]
Implemented `StageLogging` in Akka, so you can just use it instead of relying on the one in here.
See: https://github.com/akka/akka/issues/18793 

To be removed: https://github.com/akka/reactive-kafka/blob/master/core/src/main/scala/akka/kafka/internal/StageLogging.scala

**Comment by ktoso** [comment]
This is since 2.4.12

**Comment by jacobtardieu** [comment]
I'll take it!

**Comment by jacobtardieu** [comment]
This has been done, the issue can be closed.

**Comment by ktoso** [comment]
Thanks for the ping here :)
