### ISSUE TITLE
Propagate KafkaConsumerActor - WakeupException limit exceeded, stopping

### ISSUE THREAD

**Issue by jonathanvm13** [akka/reactive-kafka#252]
Hi!

I am using a Consumer with a WebSocket in Play Framework 2.5.9 to send real time messages to frontend client. The problem is that when the error `KafkaConsumerActor - WakeupException limit exceeded, stopping`  happen (For any reason), it is not propagated to close the websocket (it's a akka Flow) connection with client, because I need to send that information to the client to try to restart the ws connection or at least that the client knows that exist an connection error and it knows that the real time messages will not be sent until that the consumer will be connected with kafka successfuly. How can I  handle the KafkaConsumerActor error to propagate the error and close the websocket connection immediately ? 

```scala
def getManagerMapWebSocket = WebSocket.acceptOrResult[Any, JsValue] { request =>
  request.session.get("user") match {
    case None => Left(Future.successful(Forbidden))
    case Some(_) => Right {
      lazy val publisher =
        Consumer
          .plainSource(
            ConsumerSettings(actorSystem, new GenericDeserializer[KafkaManagerKey], new GenericDeserializer[JsValue])
              .withBootstrapServers("localhost:9092")
              .withGroupId("RandomGroupId")
              .withClientId("RandomClientId"),
            Subscriptions.topics(Set("RandomTopic"))
          )
          .map[JsValue] { msg =>
          val le_type = s"map_${msg.key.eventType}"

          Json.obj(
            "type" -> le_type,
            "data" -> msg.value
          )
        }

      Future.successful(Flow.fromSinkAndSource(akka.stream.scaladsl.Sink.ignore, publisher))
    }
  }
}
```

Thanks!

**Comment by kciesielski** [comment]
When the limit gets exceeded, consumer stage gets terminated. I wrote an isolated test with flow constructed like yours:
```scala
val failingMock = new FailingConsumerMock[K, V](new WakeupException(), failOnCallNumber = 1, 2, 3)
    val msg = createMessage(1)
    failingMock.enqueue(List.fill(3)(toRecord(msg)))
    val src = testSource(failingMock)
    val probe = Source(1 to 100)
      .via(Flow.fromSinkAndSource(Sink.ignore, src))
      .toMat(TestSink.probe)(Keep.right)
      .run()

    probe
      .request(1)
      .expectError()

    probe.cancel()
```

Looks like from our perspective it works like expected.  I'll try to check how the `OnError` emitted by the flow is then handled by Play internals.

**Comment by kciesielski** [comment]
@jonathanvm13 I tested this case on sample project by James Ward (https://github.com/jamesward/hello-play-kafka). I modified it a bit only to make it runnable without Heroku and SSL. I started it with local Kafka, then I killed Kafka. I can see in logs that the underlying consumer is trying to retry and finally fails. Errors seems to be captured by Play's error handling:
```
[warn] a.k.KafkaConsumerActor - Consumer interrupted with WakeupException after timeout. Message: null. Current value of akka.kafka.consumer.wakeup-timeout is 5000 milliseconds
[error] a.k.KafkaConsumerActor - WakeupException limit exceeded, stopping.
[error] p.c.s.c.WebSocketFlowHandler - WebSocket flow threw exception
java.lang.Exception: Consumer actor terminated
	at akka.kafka.internal.SingleSourceLogic$$anonfun$preStart$1.apply(SingleSourceLogic.scala:54)
...
```

**Comment by cerst** [comment]
@jonathanvm13 @kciesielski I encountered a similar problem using the following stream:
```
Consumer
      .plainSource(consumerSettings, Subscription.topics(topics)
      .map(toPlainConsumerRecord)
      .to(
        Sink.actorRefWithAck(sink, OnInit, NextRecord, onComplete, onFailure)
      ).run()
```

If i stop Kafka (in my case, a local VM Docker container), the last thing i can see in the logs is (after the consumer has exceeded its wakeup retries):
```
ERROR  WakeupException limit exceeded, stopping.
````

The stream remains in this seemingly blocking state until Kafka becomes available again (i've waited for about 2 minutes before starting the container again without anything happening). As soon as that's the case, the stream "resumes" by failing as expected (i.e. it passes the consumer exception downstream).

Not sure if it is related, but i can see a few of the following warnings right after "resuming":
```
WARN  o.a.kafka.common.protocol.Errors  - Unexpected error code: 38
WARN  o.apache.kafka.clients.NetworkClient  - Error while fetching metadata with correlation id [...]
```

Interestingly enough, you can work around that bevhiour by using another source (tested with _committableSource_). In that case, the consumer exception is passed downstream as expected (i.e. right after the wakeup limit has been exceeded). 
So, the problem may reside within the implementation of _plainSource_.

**Comment by kciesielski** [comment]
@cerst if your consumer exceeds wakeup retries, the materialized future should fail. Do you handle this with `future.onFailure`?

**Comment by Matt343** [comment]
I am also seeing this behavior sometimes when using a `committablePartitionedSource`. I am using `future.onComplete`, so it should definitely be firing on either completion or failure, but that never occurs.

**Comment by jpeel** [comment]
I'm seeing this in a different way. I've tried both restart supervision strategy and resume supervision strategy, but when either of those is triggered, I log a message about it. I'm never seeing a message logged when the Wakeup limit is reached. It is like the Terminated message either isn't reaching the SingleSourceLogic's stage actor or the ref inside of the Terminated message does not match the consumer.

**Comment by jpeel** [comment]
Upon further investigation I found that the issue I am seeing is that the SingleSourceLogic doesn't heed the supervision strategy at all. It always does a stop and we appear to be getting some strange things by mixing one element (the kafka consumer source) that does the stopping strategy with other elements that are doing the resuming strategy.

**Comment by chbatey** [comment]
One reason your stream may appear to be blocked is that when the `KafkaConsumerActor` hits the `KafkaConsumerActor - WakeupException limit exceeded` it then shuts its self down. Which in turns calls `KafkaConsumer.close` which by default blocks waiting for the pending commits etc.

Doing some experimenting if I take kafka down after a successful connection then the materialised future doesn't fail for me for 30s after we hit the limit. If i have kafka down from the start then it fails as soon as the limit has been hit. All that time is in `KafkaConsumer.close()`

We have `akka.kafka.consumer.close-timeout` but that doesn't appear to be used. Raising a PR now to fix this.

We might want a happy shutdown timeout where we want to give it more time tand a failure timeout where we aren't expecting a graceful shut down, WDYT?
