### ISSUE TITLE
Expose offsetsForTimes function from kafkaConsumer

### ISSUE THREAD

**Issue by jvvasques** [akka/reactive-kafka#267]
At Talkdesk we're using Kafka and we need to have access to a kafkaConsumer primitive to get [offsets given a timestamp.](https://kafka.apache.org/0101/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#offsetsForTimes(java.util.Map))

I've discovered this project and I want to integrate it in our Kafka pipeline. Are you open to receive a PR to add support to this Kafka low-level primitive?

**Comment by kciesielski** [comment]
@jvvasques of course, PRs are most welcome :) BTW: does this call to `consumer.offsetsForTimes()` have to be synchronized with `poll` and `commit`?

**Comment by jvvasques** [comment]
I believe no. According to the [code and documentation](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java#L1426) the call to `consumer.offsetsForTimes()` is blocking and it does not interfere with `pool` and `commit`

**Comment by 13h3r** [comment]
How do you use such offsets? Are they used once during stream start to setup initial offsets or they are used on regular basis during data processing?

**Comment by jvvasques** [comment]
@13h3r we plan to use those offsets to setup the initial position in kafka when starting the stream

**Comment by ennru** [comment]
Looks like #300 which was released in 0.17 implemented this.
Please re-open if something is missing.
