### ISSUE TITLE
KafkaConsumer at branch 0.8 consumes from only 1 stream with numThreads>1

### ISSUE THREAD

**Issue by IgorBerman** [akka/reactive-kafka#269]
I know that 0.8 branch is not a main point of interest, however there are plenty of production setups with kafka 0.8, so I've tried to use this branch.
At least for documentation reasons I've decided to report following behavior:

It's possible to pass parameter of number of threads to ConsumerConfiguration.
KafkaConsumer has following code connector.createMessageStreamsByFilter(filterSpec, props.numThreads, new DefaultDecoder(), props.decoder).head, so when it's created with numThreads = 4 it will return multiple streams(i.e. 1 per consumer thread), however current implementation will take only 1 stream(head)
The problem is caused since those 4 threads will be created underline and will take ownership of kafka topic partitions(e.g. total 4 partitions), so effectively only 1 partition will be "consumed" since only "head" stream is used in KafkaConsumer
In source repo(elodina/scala-kafka) that this KafkaConsumer was taken from it's changed to work with only 1 thread(at least in master)

I've seen in other issue, that suggested approach to get "multithreaded" consumption is to create several Sources, but this is not "official" and then might be better to drop support of number of threads parameter completely?(as in elodina repo)

**Comment by 2m** [comment]
Closing this ticket due to inactivity. Please re-open this ticket with more information if you still find the original issue relevant.
