### ISSUE TITLE
Sub source of plainPartitionedSource doesn't complete when its partition gets revoked

### ISSUE THREAD

**Issue by elkozmon** [akka/reactive-kafka#290]
Hi,

I am experiencing an issue when auto-rebalance kicks in and my plainPartitionedSource consumer "loses" some partitions, their sub sources don't complete as they are supposed to. Later with the help of the debugger I learned that when the `shutdown()` method is called upon the SubSourceStage, its control callback is not initialized and therefore won't shutdown. SubSourceStage lacks superclass `preStart()` method call which initializes this control callback, so I added it and it seemed to do the trick.

**Comment by patriknw** [comment]
@elkozmon could you create a pull request?

**Comment by elkozmon** [comment]
@patriknw [sure](https://github.com/akka/reactive-kafka/pull/294)
