### ISSUE TITLE
[Config] Possible stackoverflow in ConfigSettings class

### ISSUE THREAD

**Issue by arpanchaudhury** [akka/reactive-kafka#307]
There is a possibility of **stackoverflow** exception in **parseKafkaClientsProperties** method of **ConfigSettings** class. Presently it has an inner method named **collectKeys** which is recursive. Should we make it tail recursive instead?

**Comment by arpanchaudhury** [comment]
submitting PR https://github.com/akka/reactive-kafka/pull/308

**Comment by patriknw** [comment]
looks like this was fixed, merged
