### ISSUE TITLE
Shareable KafkaConsumerActor will close itself after timeout if no Consumer attaches quickly enough

### ISSUE THREAD

**Issue by jrudolph** [akka/reactive-kafka#311]
According to the [documentation](http://doc.akka.io/docs/akka-stream-kafka/current/consumer.html#sharing-kafkaconsumer) you can create a shared `KafkaConsumerActor`. If you don't manage to attach some consumers to it quickly enough it will fail with a timeout exception on the next poll.

(This was reported to us by a customer still on 0.12. Will report back if that's still an issue on 0.16)

**Comment by 2m** [comment]
Still waiting for the OP to deliver. :)

Closing this ticket due to inactivity. Please re-open this ticket with more information if you still find the original issue relevant.
