### ISSUE TITLE
Improve instructions on closing a consumer graph

### ISSUE THREAD

**Issue by iravid** [akka/reactive-kafka#313]
Hi,

Opening this to check if we're reading things right in the code. It appears that given a graph such as this (pardon the abbreviated function calls):
```
val (consumerControl, graphCompletion) = Consumer
    .committableSource(...)
    .map(...)
    .via(Producer.flow(...))
    .mapAsync(1)(_.commitScaladsl())
    .toMat(Sink.ignore)(Keep.both)
    .run()
```

Shutting down the graph with `consumerControl.shutdown().flatMap(_ => graphCompletion)` causes AskTimeout errors to be emitted from the mapAsync stage.

The reason is that messages may still be in flight towards the committing `mapAsync` stage, which will fail after the consumer actor has closed.

What does work properly is `consumerControl.stop().flatMap(_ => graphCompletion).flatMap(_ => consumerControl.shutdown())` as this completes the source stage and only after graph completion closes the consumer.

Is this correct? If so, I can submit a PR to improve the documentation.

**Comment by ennru** [comment]
Fixed with #433 and #478
