### ISSUE TITLE
Multiple CGs CANNOT consumer messages simultaneously on same topic(group of topics) with different partitions

### ISSUE THREAD

**Issue by chandrujsr** [akka/reactive-kafka#315]
Issue with Akka- Kafka consumer. 

Scenario 1:
I have 5 topics and each have 3 partitions. I have aka stream consuming from all 5 topics from 1 terminal(group-id is g1), when I run the another process with same akka stream with different group-id(g2) to consumer all topics, THEN, g2 consumes all messages BUT g1 stopped consuming with error message as “WakeupException limit exceeded, stopping.” 

Scenario 2:
When I try to consume with group-id(g3) from topic1 & partition0 and also topic2 & partition1, it works without any issues. But when I start another process with same aka stream with different group-id(g4) to consumer from topic3 & partition2 and also topic2 & partition2, then G3 process is stopped consuming with error message as “WakeupException limit exceeded, stopping.”  BUT G4 started consuming as expected.

Also, I tried the above 2 scenarios with different machines, each consumer group in 1 machine. But the issue still exist.

Please let me know if i am wrong

**Comment by 2m** [comment]
Closing this ticket due to inactivity. Please re-open this ticket with more information if you still find the original issue relevant.
