### ISSUE TITLE
Support for Kafka version 0.11

### ISSUE THREAD

**Issue by raboof** [akka/reactive-kafka#322]
Kafka 0.11.0.0 was released in June, can we support it side-by-side 0.10?

**Comment by abesanderson** [comment]
I'm currently testing this on a fork, and it was pretty straightforward to change.  There were a couple deprecated apis and configs, but there weren't a lot of tests in reactive-kafka which used them.  The main thing to note is that the 0.11.0 client will only support back to version 0.10.0 brokers.  Anything earlier would require an upgrade to brokers before clients can be upgraded.

**Comment by seglo** [comment]
@abesanderson I'm curious if you've pushed your work anywhere.  I'm interested in experimenting with it.  I don't see any changes in your remote GitHub fork.

https://github.com/abesanderson/reactive-kafka

**Comment by abesanderson** [comment]
@seglo It's just on another branch: https://github.com/abesanderson/reactive-kafka/tree/upgrade-kafka-0.11.0.0

**Comment by seglo** [comment]
Of course!  Thanks.

**Comment by agemooij** [comment]
I just read about the new [Record Headers feature](https://cwiki.apache.org/confluence/display/KAFKA/KIP-82+-+Add+Record+Headers) that was released with 0.11. 

That could be really useful to us. Are there any plans for implementing this new feature in the near future?

**Comment by seglo** [comment]
There's a ton of great stuff in 0.11.0.0.  My favourite is the exactly-once consume->transform->produce transactional support.  I have a little demo available here.

https://github.com/seglo/exactly-once-streams/blob/master/src/main/scala/seglo/apps/ConsumeTransformProduce.scala

I'm thinking about working on a PR for this, unless someone beats me to it.

**Comment by gabriele83** [comment]
Hi, how much time is needed to have the Kafka 0.11 integration?
Thanks

**Comment by albio** [comment]
I need also. Any news?

**Comment by albertobisello** [comment]
I have the same needs. Could you add support to Kafka 11? 
many thanks guys!

**Comment by ktoso** [comment]
Hi @kciesielski, what do you think about this?
Usually we keep 2 versions "alive" / "maintained", so this if supporting 0.11 means enough changes that we can't trivially do so in reactive-kafka 0.11 and it means calling an 0.12 we should likely call 0.10 end-of-life soon. 

- Do you know or have time to investigate how much change there is? 
- Do you think we can stop supporting reactive-kafka 0.10 soon?

**Comment by ktoso** [comment]
Seems https://github.com/abesanderson/reactive-kafka/tree/upgrade-kafka-0.11.0.0 has made some progress.

The core Akka team won't be able to help out on this in the coming month, so we'd welcome community of reactive-kafka maintainers help :)

**Comment by johanandren** [comment]
Per the comment from @jeqo in #327, https://github.com/akka/reactive-kafka/pull/327#issuecomment-317816688 

Could we keep a single version of the client, but have toggles for using the newer features and avoid having to maintain multiple versions?

**Comment by kciesielski** [comment]
@ktoso @johanandren Sounds good, I just merged #327 as [it is apparently OK](https://github.com/akka/reactive-kafka/pull/327#issuecomment-321289280) to use 11.0 client with 10.x brokers. As for new features, how do you see such a toggle?

**Comment by kciesielski** [comment]
Update: version 0.17 is now out, with #327 included. I'm closing this issue, but I'm still interested in a way to toggle features. @ktoso @johanandren could you drop a hint for such a toggle?

**Comment by ktoso** [comment]
Just plain old feature flags - booleans or configs in reference conf that we act on in code.
Nothing fancy to report here sadly ;)
