### ISSUE TITLE
Cleanly exit consumer

### ISSUE THREAD

**Issue by gasante** [akka/reactive-kafka#323]
I am using akka stream kafka consumer, and I can't figure out how to cleanly exit when all messages are read. The Done does not seems to work like the producer does.

**Comment by kciesielski** [comment]
@gasante How do you detect that all messages are read? Kafka client and reactive-kafka read continously until terminated by the client, so you need some kind of your own notion of end. After you are sure, you can terminate the stream by calling `shutdown()` on the `Control` object materialized from your `Source`.

**Comment by gasante** [comment]
Thanks!

**Comment by kciesielski** [comment]
@gasante I'll close this for now, feel free to reopen if needed.
