### ISSUE TITLE
Add a stage that collates previous values and emits them in a group (useful for At-Least-Once-Semantics)

### ISSUE THREAD

**Issue by knordstrom** [akka/reactive-kafka#325]
Unless I'm mistaken, there currently is no stage the existing API that allows a developer to gather related messages and emit them back downstream once a condition is met. This is useful in a situation where single existing message with a given offset is multiplied somewhere during the flow but ALOS is required - and thus notification that all steps involving the duplicated messages are completed.

I asked the question on StackOverflow a few days ago and nobody responded. I wrote my own solution [there](https://stackoverflow.com/questions/44961050/at-least-once-delivery-semantics-on-a-graph-with-a-record-multiplier/44961965#44961965). I have since used it in several different apps for both the situation I've outlined above and for deduplicating the results of an Interleave stage. The simplest usage example is this latter case:

    val merge = builder.add(Interleave[MyPayload](4, 1))

    val deduplicate = FlowModifications.collate[MyPayload, CommittableOffset](
        _.record.committableOffset, //identifies similar messages by offset
        _.size == merge.n                  //considers the set complete when all outlets have responded
      ).map { _.head }

    val graph = ... ~> merge ~> deduplicate ~> ...

Obviously if I've missed a better way to do this with existing API, let me know. Otherwise I would be happy to submit a PR for this.

**Comment by johanandren** [comment]
I think the stage described in the SO is pretty much exactly `Flow.groupedWithin` or `Flow.groupedWeightedWithin` while what you describe here could probably be expressed using a `Flow.statefulMapConcat`.

**Comment by knordstrom** [comment]
Not quite.

> groupedWithin(int n, scala.concurrent.duration.FiniteDuration d) 
>           Chunk up this stream into groups of elements received within a time window, or limited by the given number of elements, whatever happens first.

All this stage does is gather items within a time window. What happens if my correlated messages fall across that time window boundary? What happens if they are run previously through a stage that does not preserve order? The answer in both cases is that I end up with a series of states that do not tell me when the last "spawned" message is available.

What I'm looking for is a stage that will allow me to specify 
   a. what it means for a message to be part of a group 
   b. what it means for a group to be complete 
   c. a timeout to keep from stalling my graph 
Further, the stage in question should only push the group when it's complete. Otherwise I can't implement true ALOS because I won't have confirmation of processing all items.

Now there are no docs I can find on groupedWeightedWithin but it doesn't look like it fulfills all my criteria either from the [API](http://doc.akka.io/japi/akka/2.5.2/akka/stream/scaladsl/Flow.html). If I'm wrong about this can you be more precise - not to be pedantic, but "pretty much" and "probably" won't help me  much :D

**Comment by johanandren** [comment]
You are right sounds like neither `groupedWithin` nor `groupedWithinWeighted` does cover quite what you want to do, it's possible that some combination of stages, for example `groupBy`, `takeWhile` and `fold` could be more along what you want to do, not sure.

There are definitely docs on `groupedWeightedWithin`:  http://doc.akka.io/api/akka/current/akka/stream/scaladsl/FlowOps.html#groupedWeightedWithin(maxWeight:Long,d:scala.concurrent.duration.FiniteDuration)(costFn:Out=>Long):FlowOps.this.Repr[scala.collection.immutable.Seq[Out]]

I don't think this is a good fit for a issue in the reactive-kafka repo though. We use the issue trackers for bug reports and feature requests. I guess this could be interpreted as a feature request but I still feel that it is more of a question or open discussion.

I'd recommend using the akka-user mailing for more in depth discussions like this (I think it has a higher chance to get good feedback than SO at least): https://groups.google.com/forum/#!forum/akka-user

**Comment by knordstrom** [comment]
Oh I meant it as a feature request. At least I was offering it as such. This seems like it ought to be a fairly common requirement considering how important/powerful ALOS can be with a little idempotence thrown in.

I don't need feedback on SO, I've been using this stage in a variety of fairly complex graphs since I posted that a couple of days ago and so far it's been robust in all tests. But I can start a discussion in the mailing list if it feels too immature to be part of the project. 

Thanks for the docs, google fail on my part.

**Comment by johanandren** [comment]
Ok, thanks for clarifying. I think that such a stage, should go in [akka-stream-contrib](https://github.com/akka/akka-stream-contrib) rather than reactive-kafka as it is more general and doesn't really have anything to do with kafka as far as I can see (even if that is what you needed it for). We should really make sure it isn't solvable through composition of existing stages first though, I haven't spent enough time thinking about the problem to say for sure.

**Comment by knordstrom** [comment]
Good point. It looks to me like someone requested such a stage at https://github.com/akka/akka/issues/19395#issuecomment-221261407, which was closed and moved to https://github.com/akka/akka-stream-contrib/issues/14. I'll comment on the latter.
