### ISSUE TITLE
Consumer ignores bootstrap servers settings and goes to localhost

### ISSUE THREAD

**Issue by Tvaroh** [akka/reactive-kafka#326]
I do something like:

```scala
  val consumerSettings =
      ConsumerSettings(actorSystem, new StringDeserializer, new StringDeserializer)
        .withBootstrapServers(kafkaBootstrapServers)
        .withGroupId(???)
        .withProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest")

    Consumer.committableSource(consumerSettings, ???)
```

and it ignores whatever I pass as `kafkaBootstrapServers` and goes straight to `localhost:9092`. Am I doing something obviously wrong?

**Comment by Tvaroh** [comment]
Anybody?

**Comment by ilucker** [comment]
@Tvaroh it should work. Perhaps some issues in your configuration. Could you share more details. A basic project setup where it can be reproduced could be very helpful.

**Comment by patriknw** [comment]
I guess we can close this. If it was an issue in the library nobody would be able to use it.
