### ISSUE TITLE
Support manual partition-offset assignment while retaining Kafka's rebalancing-functionality in Consumer

### ISSUE THREAD

**Issue by cstub** [akka/reactive-kafka#328]
Like others (https://github.com/akka/reactive-kafka/issues/241) we need to initialize Kafka-offsets from an external storage while retaining the rebalancing-functionality of Kafka.

To support this functionality with Reactive-Kafka we propose the following extensions to the existing Consumer-API:
1) Implementation of a new `Source`-stage `topicPartitionAssignmentSource` which emits objects of `TopicPartitionAssignment` that indicate if a `TopicPartition` was assigned or revoked to the current consumer. Objects of type `TopicPartitionAssignment` are either `TopicPartitionAssigned` or `TopicPartitionRevoked`, where `TopicPartitionAssigned` contains the offset with which the `TopicPartition` should be initialized before consuming messages.
  
2) Implementation of a new `Flow`-stage `plainTopicPartitionAssignmentFlow` which accepts elements of `TopicPartitionAssignment` and emits `Source`s for each received `TopicPartitionAssigned`.
Prior to requesting messages for the given `TopicPartition` from Kafka the `KafkaConsumer#seek()` method is used to initialize the offset depending on the `Offset` given in `TopicPartitionAssigned`.
 
An offset can have the following values:
- Auto: use the offset provided by Kafka
- Beginning: consume messages from the beginning of the partition (will invoke `KafkaConsumer#seekToBeginning()`)
- End: consume messages from the end of the partition (will invoke `KafkaConsumer#seekToEnd()`)
- Position: consume messages from the given offset position (will invoke `KafkaConsumer#seek()`)

Upon receiving a `TopicPartitionRevoked` the corresponding source is shutdown.

Usage:
```
Consumer.topicPartitionAssignmentSource(settings, Subscriptions.topics("topic"))
  .mapAsync(1) {
    case tp @ TopicPartitionAssigned(_, topicPartition, _) => loadOffset(topicPartition).map(o => tp.copy(offset = Offset.Position(o)))
    case tp => Future.successful(tp)
  }
  .via(Consumer.plainTopicPartitionAssignmentFlow[String, Long]())
  .flatMapMerge(1, _._2)
  .via(business)
  .mapAsync(1)(m => storeOffset(m.topic(), m.partition(), m.offset()))
  .runWith(Sink.ignore)
```

Definition:
```
sealed trait Offset
object Offset {
  case object Auto extends Offset
  case object Beginning extends Offset
  case object End extends Offset
  case class Position(position: Long) extends Offset
}

sealed trait TopicPartitionAssignment
case class TopicPartitionRevoked(topicPartition: TopicPartition) extends TopicPartitionAssignment
case class TopicPartitionAssigned(consumer: ActorRef /*should be private*/, topicPartition: TopicPartition, offset: Offset = Offset.Auto) extends TopicPartitionAssignment

object Consumer {
  def topicPartitionAssignmentSource[K, V](settings: ConsumerSettings[K, V],
                                           subscription: AutoSubscription): Source[TopicPartitionAssignment, Control]

  def plainTopicPartitionAssignmentFlow[K, V](): Flow[TopicPartitionAssignment, (TopicPartition, Source[ConsumerRecord[K, V], NotUsed]), Control]
}
```

This API behaves the same way as `Consumer.plainPartitionSource` but separates the process of topic-partition assignment and creation of the sub-sources into two steps, allowing the client to add stream-stages which initialize offsets from external sources between the `topicPartitionAssignmentSource` and `plainTopicPartitionAssignmentFlow`.

The `Consumer.plainPartitionedSource` can then be defined in terms of the new API, by combining the new `topicPartitionAssignmentSource` and `plainTopicPartitionAssignmentFlow`.

```
def plainPartitionedSource[K, V](settings: ConsumerSettings[K, V],
                                 subscription: AutoSubscription): Source[(TopicPartition, Source[ConsumerRecord[K, V], NotUsed]), Control] = {
  topicPartitionAssignmentSource[K, V](settings, subscription)
    .via(plainTopicPartitionAssignmentFlow[K, V]())
}
```

In addition to the new Consumer-APIs, convenience-methods for
- `Consumer.plainPartitionedSource` and
- `Consumer.plainSource`

could be created which use `Future`s to load the offsets of an assigned `TopicPartition`.
These methods could also be defined in terms of the new API:
```
object Consumer {
  def plainSource[K, V](settings: ConsumerSettings[K, V],
                        subscription: AutoSubscription,
                        f: TopicPartition => Future[Offset]): Source[ConsumerRecord[K, V], Control]

  def plainPartitionedSource[K, V](settings: ConsumerSettings[K, V],
                                   subscription: AutoSubscription,
                                   f: TopicPartition => Future[Offset]): Source[(TopicPartition, Source[ConsumerRecord[K, V], NotUsed]), Control]
}
```

What do you think of this approach?

**Comment by patriknw** [comment]
@cstub and others, take a look at the PR https://github.com/akka/reactive-kafka/pull/367 and see if it solves what you need

**Comment by cstub** [comment]
@patriknw This PR meets all our requirements. Great addition! I guess #328 can be closed then.

**Comment by patriknw** [comment]
Thanks for confirming. We'll close when it has been merged.
