### ISSUE TITLE
Partitioned consumer has RequestMessages race condition

### ISSUE THREAD

**Issue by charles-crain** [akka/reactive-kafka#330]
I am seeing the issue described in this post:
https://groups.google.com/forum/#!msg/akka-user/WwHAvHCKTiE/RbVMdV6dAwAJ

Note this was not me making this post but I am seeing the issue.  As the post says, even building against the latest master does not fix the issue.

Details:
- The message does print out transiently when consumers enter or leave the consumer group, which as I understand is normal
- However in some cases (intermittently) a consumer will get in a state where it repeatedly prints this message forever.  When in this state it does not receive any messages, and other consumers do not receive the messages from the partitions that this consumer is assigned to.

If it helps, we can reproduce it (not every time but often) by bringing up many consumers in the same consumer group at once.  Bringing up one consumer at a time and waiting for things to settle seems to avoid the bug most of the time, but it still happens some.

**Comment by fchaillou** [comment]
Hello,
I confirm that this occurs to us as well. When it happens, it logs it infinitely until we restart the service.
Fabien

**Comment by charles-crain** [comment]
Just submitted a PR that fixes the issue for me.
