### ISSUE TITLE
Consumers consuming at a low rate

### ISSUE THREAD

**Issue by amitpaz** [akka/reactive-kafka#334]
I have encountered a very strange situation where my consumers were consuming at a very slow rate - this was resolved only by chunking events (using the grouped method)

Can someone please help me understand why this helped and how can i improve my consuming throughput avoiding using grouping method?

1) No partition rebalancing was noticed 2) Events size are 30-100 KB ~
2) I'm using akka-stream 2.4.18, akka-stream-kafka 0.16, Scala 2.11

This is how i defined my consumer:

```
 private val consumerSettings = ConsumerSettings(actorSystem,
    new ByteArrayDeserializer, new StringDeserializer)
    .withBootstrapServers(KAFKA_BOOTSTRAP_SERVERS)
    .withGroupId(etl_group_id)
    .withProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG,"earliest")
    .withProperty(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, "true")
    .withProperty(ConsumerConfig.MAX_PARTITION_FETCH_BYTES_CONFIG, "4194304")
    .withMaxWakeups(24 * 60)
    .withWakeupTimeout(60 seconds)
```

Consumer initialization code:

```
def init(): Unit = {
    Consumer
        .committableSource(consumerSettings, Subscriptions.topics(ETL_TOPIC_NAME))
        .mapAsync(PARALLELISM_FACTOR)((msg) => addEvents(msg))
        .runWith(Sink.ignore)(materializer)
```

Consumer initialization code with grouping:

```
def init(): Unit = {
    Consumer
        .committableSource(consumerSettings, Subscriptions.topics(ETL_TOPIC_NAME))
        .groupedWithin(200, 1 seconds)
        .mapAsync(parallelism_factor)((msg) => addEvents(msg))
        .runWith(Sink.ignore)(materializer)
```

**Comment by 2m** [comment]
Closing this ticket due to inactivity. Please re-open this ticket with more information if you still find the original issue relevant.
