### ISSUE TITLE
Document how to implement simple health check/ping

### ISSUE THREAD

**Issue by rory-work** [akka/reactive-kafka#345]
Some documentation on how to implement a simple health check/ping would be useful. 

Something like the following, but using reactive-kafka:

```
import org.apache.kafka.clients.consumer.KafkaConsumer
...
val properties = new Properties()
properties.put("bootstrap.servers", "kafka:9092")

val kafkaConsumer = new KafkaConsumer[String, String](properties)
kafkaConsumer.partitionsFor("my-topic") //will fail if Kafka is unavailable
```

**Comment by 2m** [comment]
In the latest release we added support for metadata: https://doc.akka.io/docs/akka-stream-kafka/current/consumer-metadata.html

You can use that for a healt-check.
