### ISSUE TITLE
Fix typo in Doc example - StreamWrapperActor

### ISSUE THREAD

**Issue by muditsin** [akka/reactive-kafka#346]
https://github.com/akka/reactive-kafka/blob/5f013a6b45ca4eb006d232c9ad522418bbce358d/docs/src/test/scala/sample/scaladsl/ConsumerExample.scala#L391
It should be 'graceful', and not 'gracceful'?

**Comment by kciesielski** [comment]
@muditsin Thanks, next time feel free to submit a pull request and we'll merge straight away.
