### ISSUE TITLE
Rewrite error handling documentation to use the new RestartSource

### ISSUE THREAD

**Issue by patriknw** [akka/reactive-kafka#348]
... instead of actors. Because it's simpler.

https://doc.akka.io/docs/akka-stream-kafka/current/errorhandling.html#restarting-the-stream

**Comment by seglo** [comment]
I have an example of this for the docs in PR #420 that could be generalized.  Perhaps #372 could be updated to include side effecting out the `Control` materialized value so it can be used to orchestrate stream shutdown from the outside.

https://github.com/seglo/reactive-kafka/blob/transactions/docs/src/test/scala/sample/scaladsl/TransactionsExample.scala#L29..L60

/cc @jjst
