### ISSUE TITLE
Using takeWhile terminates CommittableSource while commits are in progress

### ISSUE THREAD

**Issue by mina-mishriky-ck** [akka/reactive-kafka#357]
We are having an issue when using a `takeWhile`operation on a `CommittableSource` to consume messages up to a certain offset.
The graph simply looks like:
`CommittableSource` ~~> `takeWhile(...)` ~~> `Flow` (performs logic and commits offsets) ~~> `SinkActor`

The issue that we are facing is once the `takeWhile` condition is reached, the source is canceled immediately, which results in commits failing for offsets that had originally passed the `takeWhile` condition. The error message is `"akka.kafka.KafkaConsumerActor$Internal$Commit"`

I believe the expected behavior should be to wait for outstanding offsets to be committed before shutting down. We are open to alternative approaches for consuming up to a certain offset, if better ones exist.

**Comment by mina-mishriky-ck** [comment]
Any thoughts on this?

**Comment by pierangeloc** [comment]
I encountered a similar issue when using simple `take`. I have a simple flow that consumes from `sourceTopic`, transforms the string payloads and puts them in `targetTopic`.

```scala
Consumer.committableSource(consumerSettings, Subscriptions.topics(sourceTopic))
    .take(10)
    .map { msg =>
      ProducerMessage.Message(new ProducerRecord[Array[Byte], String](
        targetTopic,
        msg.record.value + "-processed"
      ), msg.committableOffset
      )
    }
    .via(Producer.flow(producerSettings))
    .map(_.message.passThrough)
    .batch(max = 20, first => CommittableOffsetBatch.empty.updated(first)) { (batch, elem) =>
      batch.updated(elem)
    }
    .mapAsync(3)(_.commitScaladsl())
    .runWith(Sink.ignore)
```
After the run, if I run the graph again it restarts from the same offset. By inspecting the offset in Zookeeper for the consumer group, I see that offset is not committed.
Removing the `take` and letting it consume all available elements from source topic solves the problem.

**Comment by ennru** [comment]
Is this solved by the `commitsInProgress` logic in `KafkaConsumerActor`?
Or is this different to #166 
See test cases in #490

**Comment by 2m** [comment]
Closing this ticket due to inactivity. Please re-open this ticket with more information if you still find the original issue relevant.
