### ISSUE TITLE
[Question] Unit Testing

### ISSUE THREAD

**Issue by nolledge** [akka/reactive-kafka#359]
Hi,
I'am new to Apache Kafka and Akka Streams Kafka seems to be the perfect fit for a the use as a middleware in a microservice environment, which is in majority based on Play applications. 

I prototyped a small App with a Consumer and a Publisher, communicating via JSON and that was pretty straight forward. But when it comes to unit testing I become a little helpless. Is it possible to run the tests in a lightweight fashion and not with a running Kafka Cluster or an embedded server (https://github.com/manub/scalatest-embedded-kafka)? I also found this project which looked promising: https://github.com/manub/scalatest-embedded-kafka, but I was not able to test my Consumer with it. Isn't that the right tool? I'am a little confused.

**Comment by raboof** [comment]
Hi @nolledge, thanks for your question! We mostly use github issues for bugs/features, for questions like these our gitter channel at gitter.im/akka/akka might be more suitable.

We indeed also use scalatest-embedded-kafka - but I'm not sure of the specifics myself. For even more lightweight unittests you might be able to test some of your code without actually going through Kafka, instead composing test streams with our testkit as documented at https://doc.akka.io/docs/akka/current/scala/stream/stream-testkit.html
