### ISSUE TITLE
Doc issue in ProducerMessage.scala

### ISSUE THREAD

**Issue by ManikandanPitchai** [akka/reactive-kafka#374]
https://github.com/akka/reactive-kafka/blob/3669bc2fd55d5846f104b202be749e2b86860211/core/src/main/scala/akka/kafka/ProducerMessage.scala#L16

Is it not Producer#commitableSink and Producer#flow?

**Comment by ktoso** [comment]
Thanks for reporting;
Solved by @Philippus in  #384
