### ISSUE TITLE
How to re run a failed message in reactive kafka 0.8.2.2

### ISSUE THREAD

**Issue by DhavalKolapkar** [akka/reactive-kafka#378]
I want to re-publish the messages for x no of times which failed to process. I see the manual commit code:

val consumerWithOffsetSink = kafka.consumeWithOffsetSink(consumerProperties)
Source.fromPublisher(consumerWithOffsetSink.publisher)
.map(processMessage(_)) // your message processing
.to(consumerWithOffsetSink.offsetCommitSink) // stream back for commit
.run()
However, how to handle exceptions in the processMessage() method? I would like to handle the exception and ask kafka to re run the message 3 times. If it still fails after 3 times, discard it.

**Comment by ennru** [comment]
This is more a question than an issue, if the question persists, please use [the users' forum](https://discuss.lightbend.com/c/akka/streams-and-alpakka).
