### ISSUE TITLE
Use embeded Kafka + Zookeeper for tests

### ISSUE THREAD

**Issue by kciesielski** [akka/reactive-kafka#38]
Evaluate and try to switch to something like this: https://gist.github.com/fjavieralba/7930018

**Comment by manub** [comment]
I worked on this in my spare time - https://github.com/manub/scalatest-embedded-kafka - maybe it's something that can help.

**Comment by kciesielski** [comment]
Looks promising, thanks @manub :) I'll try to add it.

**Comment by akauppi** [comment]
Hi guys, did something come out of this? I'd love to be able to just `sbt test` reactive-kafka, without setting up anything.

I was thinking of suggesting something like [docker-it-scala](https://github.com/whisklabs/docker-it-scala) that allows ScalaTest to run servers within Docker containers, but an embedded Kafka would be even better (i.e. not require any additional installs).

**Comment by kciesielski** [comment]
@akauppi No, this is still not explored with reactive-kafka but there are no blockers to try it (except my lack of free time :)

**Comment by manub** [comment]
I'm afraid I'm lacking a lot free time as well. I had a short go but stumbled across the fact Reactive Streams TCK requires TestNG and it's not straightforward to have an Embedded Kafka shared across all the tests which are running in parallel.

**Comment by mjkrumlauf** [comment]
@manub @akauppi Check out this attempt at embedded Kafka.  I wasn't entirely successful but it might be of some help - https://github.com/mjkrumlauf/reactive-kafka/tree/embedded-kafka-test

**Comment by akauppi** [comment]
If you're interested, I've used [docker-it-scala](https://github.com/whisklabs/docker-it-scala) recently, with Kafka 0.9.0.0, with success. If reactive-kafka is okay having a dependence on Docker, for testing, that's a great encapsulated way to go.

Personally, I would see it as an optional way to test. Can propose a PR maybe next week, that would provide both that and the normal "I already have Kafka running here" approaches.

Any points of view, from the project?

**Comment by manub** [comment]
I'm not a maintainer of reactive-kafka but honestly I wouldn't tie it to Docker. Having an external dependency is worse than having to start the service IMHO.

**Comment by akauppi** [comment]
@manub I agree. @kciesielski has the [activator-reactive-kafka-scala](https://github.com/softwaremill/activator-reactive-kafka-scala) using an embedded Kafka + Zookeeper. It works well. So the task is simply to integrate that with the tests of reactive-akka?

**Comment by kciesielski** [comment]
@akauppi Yes, however there were some obstacles when I tried to simply re-do the integration here. I must admit it's been a while ago and I haven't noted down what's the issue exactly...

**Comment by kciesielski** [comment]
@manub I managed to run tests with your library after some tweaks (https://github.com/manub/scalatest-embedded-kafka/pull/12)

**Comment by manub** [comment]
@kciesielski I released version `0.5.0` - should appear on Maven Central soon.

**Comment by patriknw** [comment]
sounds promising, thanks

**Comment by patriknw** [comment]
@kciesielski @13h3r please set the milestone on the issues when closing so we have some track of what goes into which release, thanks

**Comment by kciesielski** [comment]
@patriknw Sure.
