### ISSUE TITLE
Allow akka.kafka.ProducerSettings to be extended

### ISSUE THREAD

**Issue by rafalmag** [akka/reactive-kafka#387]
Allow `akka.kafka.ProducerSettings` to be extended.
Right now that class is declared as final.
Right now it is very inconvenient when somebody wants to unit test the custom flow attached to a sink from `akka.kafka.scaladsl.Producer`.
Ideally to make a true unit test the real Kafka akka streams sink could be created using a mocked or fake ProducerSettings that when called `createKafkaProducer` would return a custom `org.apache.kafka.clients.producer.Producer` like `org.apache.kafka.clients.producer.MockProducer` or just some mock from mockito.

**Comment by johanandren** [comment]
If you are writing a unit test, shouldn't you rather take out the Producer sink from the equation and put something more suitable for unit testing there?

**Comment by rafalmag** [comment]
I am writing a factory function that would return a custom Sink or one of the standard akka.kafka sinks and I wanted to use the common settings API. I can revert to common java.util.Properties, but it would be nice to be able to extend akka.kafka more easily.

**Comment by ennru** [comment]
Fixed with #388
