### ISSUE TITLE
Update to Akka 2.5.8

### ISSUE THREAD

**Issue by okly91** [akka/reactive-kafka#394]
Need update to Akka 2.5.8

**Comment by raboof** [comment]
2.5.9 has actually been released - would you be up for preparing a PR?

**Comment by johanandren** [comment]
Also, note that since we keep backwards binary compatibility in Akka, the update is nice but not strictly necessary as it means you can run reactive-kafka with a newer minor version of Akka than it was built with.

**Comment by chbatey** [comment]
I upgraded to 2.5.9 as part of a separate PR
