### ISSUE TITLE
JMX metrics

### ISSUE THREAD

**Issue by h-ngo** [akka/reactive-kafka#418]
Does Reactive Kafka reports metrics through JMX? can't seem to find any resource related to it.

**Comment by h-ngo** [comment]
FYI. We are currently using reactive kafka library in Play framework.

**Comment by johanandren** [comment]
We have an open PR #338 which is about making it possible to expose metrics, won't give you JMX out of the box but will make it possible to publish the metrics as JMX if you want.

**Comment by ranjanibrickx** [comment]
Hello, is there any update on this? We are interested in reporting on the consumer and producer JMX metrics.

**Comment by ennru** [comment]
Thank you for pointing this out.
This functionality is available in 0.20 as of PR #338.

**Comment by ennru** [comment]
See [documentation](https://doc.akka.io/docs/akka-stream-kafka/current/consumer.html#accessing-kafkaconsumer-metrics)
