### ISSUE TITLE
Expose metadata retrieving functions of Consumer in KafkaConsumerActor

### ISSUE THREAD

**Issue by dsitte-h** [akka/reactive-kafka#422]
List of functions to expose:
- `listTopics()`
- `partitionsFor()`
- `beginningOffsets()`
- `endOffsets()`
- `offsetsForTimes()`

Example usage:
```scala
//Consumer is represented by actor
val consumer: ActorRef = system.actorOf(KafkaConsumerActor.props(consumerSettings))

// Retrieve metadata
val endOffsets = for {
  partitions <- consumer ? GetPartitonsFor("topic").mapTo[List[PartitionInfo]]
  endOffsets <- consumer ? endOffsets(partitions).mapTo[Map[TopicPartition, Long]]
} yield {
  endOffsets
}

// wait for endOffsets Future

//Manually assign topic partition to it
Consumer
  .plainExternalSource[Array[Byte], String](consumer, Subscriptions....)
  .via(business)
  .runWith(Sink.ignore)
```
The point is being able to use the same underlying KafkaConsumer for retrieving metadata and consuming.  

A side-effect is that Kafka connection is established upon metadata retrieval, possible connection errors can be (and need to be!) handled before the consumer graph is even created.

Willing to contribute PR.

**Comment by schrepfler** [comment]
It would be nice if we would be able to extract headers as well.

**Comment by dsitte-h** [comment]
Headers are per message, you can access them on `ConsumerRecord`:

https://github.com/apache/kafka/blob/88da81b9454183955f34b822588f0f1ee7e9dcae/clients/src/main/java/org/apache/kafka/clients/consumer/ConsumerRecord.java#L155

(Headers were introduced in Kafka v0.11)

**Comment by 2m** [comment]
Fixed in https://github.com/akka/reactive-kafka/pull/491
