### ISSUE TITLE
(typo) Scala example is duplicated (double paste) on External Offset Storage

### ISSUE THREAD

**Issue by michael-read** [akka/reactive-kafka#427]
on External Offset Storage : Here -> https://doc.akka.io/docs/akka-stream-kafka/current/consumer.html

**Comment by raboof** [comment]
It looks like those were 2 examples smashed together, one showing  `Subscriptions.assignmentWithOffset` as described in the documentation text, the other showing basically the same code but with using `Subscriptions.assignmentOffsetsForTimes`. I'd say `Subscriptions.assignmentOffsetsForTimes` is not really suitable for this at all.

**Comment by ennru** [comment]
Solved by #428
