### ISSUE TITLE
Consume messages from multiple streams when numThreads passed

### ISSUE THREAD

**Issue by Yoda-The-master** [akka/reactive-kafka#44]
Right now, the kafka consumer is using only one stream returned from kafka-client.
https://github.com/softwaremill/reactive-kafka/blob/master/core/src/main/scala/kafka/consumer/KafkaConsumer.scala#L19

It should consume from all the streams, and each of the consuming part should run in seperate thread.
We can see examples here: http://stackoverflow.com/questions/23590808/apache-kafka-kafkastream-on-topic-partition

**Comment by 13h3r** [comment]
Do we really need thread management? Why not using streams operators?
