### ISSUE TITLE
Unable to stop reactive kafka 0.8 consumer

### ISSUE THREAD

**Issue by kolapkardhaval** [akka/reactive-kafka#443]
I am creating a kafka consumer as below:
val kafka = new ReactiveKafka()
 val source =   kafka.consume(consumerProperties)
 Source.fromPublisher(source).to(sink).run()

However, I need to stop the consumer after consuming 100 messages or after an hour. How do I do it?

**Comment by ennru** [comment]
Later versions of this library materialize a `Control` instances which can be used to shut down the consumer. Please upgrade to the current version.

The "100 messages" requirement can be achieved by `.take(100)`.

**Comment by ennru** [comment]
The "Akka standard" solution to complete a stream from the outside is the use of a [KillSwitch](https://doc.akka.io/docs/akka/current/stream/stream-dynamic.html#controlling-graph-completion-with-killswitch).

Please direct this kind of questions to the [discuss forum](https://discuss.lightbend.com/c/akka/streams-and-alpakka).
