### ISSUE TITLE
wakeup-debug should default to false

### ISSUE THREAD

**Issue by agemooij** [akka/reactive-kafka#451]
We have been noticing a lot of huge stack dumps in our code that uses reactive-kafka, especially when deployed on Kubernetes. It appears these stack dumps are created based on the `wakeup-debug` setting, which defaults to `true`. 

I would suggest that the `wakeup-debug` setting, which can produce enormous amounts of logging volume, should default to false.

**Comment by agemooij** [comment]
To be precise, the setting is `akka.kafka.consumer.wakeup-debug`, with the following definition in reference.conf:

```
  # If enabled log stack traces before waking up the KafkaConsumer to give
  # some indication why the KafkaConsumer is not honouring the poll-timeout
  wakeup-debug = true
```

Shown in the docs here:

https://doc.akka.io/docs/akka-stream-kafka/current/consumer.html#settings

**Comment by patriknw** [comment]
I agree that the right default is `fals`e, but since we got so many issue reports just saying "it doesn't work" we wanted to gather information about what the reasons for the blocking would be.

**Comment by agemooij** [comment]
OK, so you set it to true on purpose to collect data? When are you planning o set it back to false?

We have explicitly set the setting to `false` for now, so big rush here. Just curious.

**Comment by 2m** [comment]
Instead of printing thread-dump on every wakeup, it will now do it when number of wakeups is more than max-wakeups/2. So we can keep wakeup-debug set to `true` by default to still have the option to collect the data and not being that verbose in normal operations.

**Comment by mr-git** [comment]
what will happen, if `max-wakeups` is set to `0`?
