### ISSUE TITLE
Transactions: create benchmarks

### ISSUE THREAD

**Issue by ennru** [akka/reactive-kafka#461]
With the new support to transfer between Kafka topics transactionally, it would be great to create some benchmarks on that functionality.

**Comment by ennru** [comment]
cc @seglo

**Comment by 2m** [comment]
Ahh, thanks for creating the ticket!

**Comment by seglo** [comment]
Sure. Did you want me to submit a PR or are you or @2m working on it?

**Comment by 2m** [comment]
I am not currently working on it. So if you @seglo could create a PR that would be awesome!

**Comment by seglo** [comment]
Sounds good.  I'll work on it this week.

**Comment by ennru** [comment]
Implemented with #481 and #483
