### ISSUE TITLE
Stopping KafkaConsumerActor using Stop message which is now package private to kafka

### ISSUE THREAD

**Issue by kpritam** [akka/reactive-kafka#499]
Sharing the KafkaConsumer instance section from [Consumer.md](https://github.com/akka/reactive-kafka/blob/master/docs/src/main/paradox/consumer.md) shows stopping KafkaConsumerActor using
KafkaConsumerActor.Stop message. But seems like Stop is moved to KafkaConsumerActor.Internal which is package private to kafka.

It should either be exposed or documentation can be improved and say stop actor using PoisonPill or any other idiomatic way.

**Comment by ennru** [comment]
The Stop message should still be used, it is not private.
See https://doc.akka.io/docs/akka-stream-kafka/current/consumer.html#sharing-the-kafkaconsumer-instance

**Comment by mrwillis** [comment]
For anyone confused, this change occurred at `0.20`. If you're still using `0.19` you'll experience this.

**Comment by ennru** [comment]
Sorry if my answer sounded a bit harsh and confusing. I only just now understand that the `Stop` object used to be protected by the `private[kafka]` on `KafkaConsumerActor.Internal`.
From version 0.21 it has moved to `KafkaConsumerActor.Stop`.
