### ISSUE TITLE
How to use it as flow part instead of sink

### ISSUE THREAD

**Issue by richiesgr** [akka/reactive-kafka#50]
Hi

May be not a good place to ask this. But I can't figure out how to use the subscriber as other place than Sink. I want to use the producer as flow part not sink.
So this working flow.to(Sink(subscriber))
But how I can use like flow.via(subscriber).via ....
Then I need also to be able to throw exception out
Thanks

**Comment by dbuschman7** [comment]
I would use a Broadcast to split the flow, one output to a Kafka sink, and one to continue processing, like this : 

val broadcast = builder.add(Broadcast[YourTypeHere](2)) // number of outputs

upStream ~> broadcast ~> kafka 
broadcast ~> otherWork

NOTE: I am using the DSL and not the direct methods to build my flows

**Comment by kciesielski** [comment]
+1, broadcast seems like a good approach

**Comment by richiesgr** [comment]
Hi
I can't I need to the otherWork before sending to kafka and need to do something else after sending to kafka that's the flow !
Any other option ?

**Comment by kciesielski** [comment]
@richiesgr What do you mean by "after sending to kafka"? Do you need some sort of confirmation that the message has actually been sent there or can you just do your flow 'besides' sending to Kafka?

**Comment by richiesgr** [comment]
Yes I need to confirm that the message has been sent return back to a rest API
In fact I get a Http Request I transform what I get to valid JSON send to kafka and return back Http code
That's why I need to be a part of the flow and not just the sink

**Comment by kciesielski** [comment]
@richiesgr Maybe you can achieve what you want with solution from issue #51 ?

**Comment by 13h3r** [comment]
done in 0.11
