### ISSUE TITLE
Import could be included in the New API samples

### ISSUE THREAD

**Issue by akauppi** [akka/reactive-kafka#82]
https://github.com/softwaremill/reactive-kafka/blob/master/docs/NewAPI.md

Currently, trying to copy-paste the Core code sample, leads one to needing to decide between two Consumer classes of reactive-akka:

<img width="677" alt="screen shot 2016-02-19 at 10 39 22" src="https://cloud.githubusercontent.com/assets/1297734/13170863/ffda757c-d6f7-11e5-9d51-6ff7156f1dc4.png">

There would be two ways to avoid this:

- not use the same class name in multiple parts of reactive-akka
- providing the necessary imports in the code samples

**Comment by akauppi** [comment]
There are pretty many APIs to reactive-kafka, at the moment. Is it the intention that one of these (the `kafka2` files) would remain, or all of them?

If all, then the pros and cons of different approaches should be explained somewhere, and the approaches be clearly separated in the code, e.g. by using namespaces (as already `kafka` and `kafka2` are separate, but maybe with more descriptive names?).

**Comment by 13h3r** [comment]
From my point of view we should keep only one API. This API should provide all functionality. I call it _low level API_. 

On top of low level API we could build high level components with predefined behavior. Like consumer as `Source` without commit `In` at all. 

@kciesielski what do you think?

**Comment by 13h3r** [comment]
Current readme contains all imports
