### ISSUE TITLE
Partitioner issue with Array hashCode

### ISSUE THREAD

**Issue by cheleb** [akka/reactive-kafka#84]
AFAIU there is an issue with Partitioner

Branch 0.8:
Partitioner is a T => Option[Array[Byte]] but as Array.hashCode does not hash values, [it is not consistent for two arrays with same values](https://issues.scala-lang.org/browse/SI-1607) partitioner cannot work with [DefautPartitioner](https://github.com/apache/kafka/blob/0.8.2/core/src/main/scala/kafka/producer/DefaultPartitioner.scala).
I've fixed this issue(?) with a custom partitioner that transform Array to List:
```scala
class MyPartitioner(props: VerifiableProperties = null) extends Partitioner {
  private val random = new java.util.Random
  
  def partition(key: Any, numPartitions: Int): Int = {
    key match {
      case ab: Array[Byte] => Utils.abs(ab.toList.hashCode) % numPartitions
      case _ => Utils.abs(key.hashCode) % numPartitions
    }
    
  }
}
```

If Partitioner was  T => List[Byte] is might be easier to use.

Did I missed something ?

Thx

**Comment by kciesielski** [comment]
Indeed, this needs fixing. In the master branch, where we use 0.9 client library, partitionizer is defined as `V => Option[Int]` so it's OK. In the 0.8 branch we can change `KafkaProducer` to convert the byte array to a `List` before putting it in a `KeyedMessage`. This way we can preserve API backward compatibility.

**Comment by cheleb** [comment]
Just by upgrading the dependency to 0.8.6 I encountered an classcast exception ( LIst[Byte] does not fill well in an Array[Byte] :) during key serialization.
AFAIU now when providing partition hint I must also change the key encoder with an Encoder[List[Byte]] implementation ( just returning toArray ).

**Comment by kciesielski** [comment]
@cheleb Right, changing the encoder should help. However, I hoped that we can this problem with `hashCode` without requiring any changes by library users. I wrote a failing test now and I'm working on a fix.

**Comment by kciesielski** [comment]
@cheleb Can you test now with 0.8.7-SNAPSHOT?

**Comment by cheleb** [comment]
It works perfectly with 0.8.7-SNAPSHOT (3e8cf0d5f0d4b78c8a761e924a48b50391dff480)

**Comment by kciesielski** [comment]
Thanks @cheleb. 0.8.7 is now available.
