### ISSUE TITLE
Suggestion for README order

### ISSUE THREAD

**Issue by akauppi** [akka/reactive-kafka#91]
(removed from PR #73 )

- project scope / purpose (is already there)
- Getting Started (new, includes requirements, how to run tests)
- Using (includes lines to add in `build.sbt`)
- Passing Configuration Properties to Kafka (as now)
- Controlling consumer start offset (as now)
- Working with actors (as now)
- Tuning (as now; could be called Configuration?)

**Comment by patriknw** [comment]
I think this is obsolete
